import type { Lesson, VisualEffect } from "./types";

const fb = (feedback: string, simulation = feedback, visualEffect?: VisualEffect) => ({ feedback, simulation, visualEffect });
const c = (actorId: string, useCaseId: string) => ({ actorId, useCaseId });

export const interactiveLessons: Lesson[] = [
  {
    id: "intro-machine",
    title: "Bài 0: Hệ thống tạo ra giá trị cho ai?",
    description: "Trước khi học Use Case, hãy nhìn hệ thống từ bên ngoài: một người hoặc tác nhân tương tác với hệ thống để đạt được một kết quả có ích.",
    steps: [
      {
        id: "intro-01",
        title: "Actor -> System -> Goal",
        story: "Actor -> System -> Goal. Sinh viên -> FPTU Club Management System -> Tìm được CLB phù hợp. Một sinh viên mới vào muốn tìm một CLB phù hợp với sở thích của mình. Bạn đang thiết kế hệ thống quản lý CLB để hỗ trợ sinh viên đó.",
        instruction: "Kéo các block vào đúng vùng.",
        type: "SORT_BLOCKS",
        data: {
          zones: [
            { id: "student-goal", label: "Mục tiêu sinh viên muốn đạt được" },
            { id: "internal-detail", label: "Cách làm / giao diện / xử lý bên trong" },
          ],
          blocks: [
            {
              id: "find-club",
              label: "Tìm được CLB phù hợp",
              correctZoneId: "student-goal",
              successFeedback: "Đúng. Đây là kết quả có ích mà sinh viên muốn đạt được khi dùng hệ thống.",
            },
            {
              id: "view-list",
              label: "Xem danh sách CLB",
              correctZoneId: "student-goal",
              successFeedback: "Đúng. Sinh viên có thể dùng hệ thống để xem các CLB hiện có trước khi chọn CLB phù hợp.",
            },
            {
              id: "enter-keyword",
              label: "Nhập từ khóa tìm kiếm",
              correctZoneId: "internal-detail",
              feedback: "Chưa đúng. Nhập từ khóa là thao tác trên giao diện. Nếu sau này hệ thống đổi sang gợi ý tự động hoặc tìm kiếm bằng giọng nói, mục tiêu của sinh viên vẫn là tìm được CLB phù hợp.",
            },
            {
              id: "view-detail",
              label: "Xem chi tiết một CLB",
              correctZoneId: "student-goal",
              successFeedback: "Đúng. Đây là một kết quả có ích vì sinh viên cần biết thông tin cụ thể của CLB trước khi quyết định quan tâm hoặc tham gia.",
            },
            {
              id: "search-button",
              label: "Bấm nút Search",
              correctZoneId: "internal-detail",
              feedback: "Chưa đúng. Bấm nút là thao tác UI. Nếu giao diện thay đổi, nút Search có thể không còn, nhưng mục tiêu tìm CLB vẫn giữ nguyên.",
            },
          ],
          successSimulation: "Khi xác định Use Case, hãy bắt đầu bằng mục tiêu mà Actor muốn đạt được. Trong ví dụ này, Actor là Sinh viên.",
          mixedSimulation: "Điểm quan trọng không phải là hệ thống xử lý ra sao, mà là sinh viên nhận được giá trị gì từ hệ thống.",
        },
      },
      {
        id: "intro-01b",
        title: "Tương tác đầu tiên",
        story: "Hãy làm quen với việc vẽ sơ đồ. Sơ đồ Use Case hoạt động khi Actor tương tác và kích hoạt Use Case.",
        instruction: "Nối Sinh viên với mục tiêu Tìm được CLB phù hợp, sau đó bấm Run Diagram.",
        type: "RUN_DIAGRAM_SCENARIO",
        data: {
          systemLabel: "Hệ thống FPTU",
          actors: [{ id: "student", label: "Sinh viên", kind: "human" }],
          useCases: [{ id: "find-club", label: "Tìm được CLB phù hợp", icon: "Mục tiêu" }],
          correctConnections: [c("student", "find-club")],
          scenarios: [
            {
              id: "run-01",
              title: "Sinh viên đạt mục tiêu",
              path: ["Sinh viên", "Tìm được CLB phù hợp"],
              requiredActors: ["student"],
              requiredUseCases: ["find-club"],
              requiredConnections: [c("student", "find-club")],
              feedback: "Chưa nối dây! Hãy kéo từ Sinh viên sang Tìm được CLB phù hợp để hoàn tất đường đi."
            }
          ],
          successSimulation: "Bạn đã vẽ được đường thẳng giao tiếp đầu tiên! Actor Sinh viên giờ đây có thể đạt được mục tiêu."
        }
      },
      {
        id: "intro-02",
        title: "Success Insight",
        type: "INSIGHT",
        data: {
          text: "Khi xác định Use Case, hãy bắt đầu bằng ______ mà Actor muốn đạt được. Trong ví dụ này, Actor là ______. Điều quan trọng là Actor nhận được ______ từ hệ thống: xem danh sách CLB, tìm CLB phù hợp và nắm được thông tin cần thiết trước khi quyết định tham gia hay không.",
          answers: ["mục tiêu", "Sinh viên", "giá trị"],
          finalInsight: "Khi xác định Use Case, hãy bắt đầu bằng mục tiêu mà Actor muốn đạt được. Trong ví dụ này, Actor là Sinh viên. Điều quan trọng là Actor nhận được giá trị từ hệ thống: xem danh sách CLB, tìm CLB phù hợp và nắm được thông tin cần thiết trước khi quyết định tham gia hay không.",
        },
      },
    ],
  },
  {
    id: "what-not-how",
    title: "Bài 1: Use Case là gì?",
    description: "Cinema Booking System: nhìn Use Case như mục tiêu và giá trị mà Actor muốn đạt được, không phải UI, database, API hay xử lý kỹ thuật.",
    steps: [
      {
        id: "what-01",
        title: "Xây dựng mục tiêu đặt vé",
        story: "Bạn đang thiết kế Cinema Booking System. Một khách hàng mở hệ thống vì muốn đặt vé xem phim cuối tuần. Hãy kéo vào khung hệ thống những thẻ thể hiện mục tiêu người dùng thật sự muốn đạt được.",
        instruction: "Kéo các thẻ phù hợp vào khung Cinema Booking System, sau đó bấm Run.",
        type: "DRAG_TO_BOUNDARY",
        data: {
          boundaryLabel: "Cinema Booking System",
          zones: [
            { id: "inside", label: "Trong System Boundary" },
            { id: "exclude", label: "Không đưa vào Use Case Diagram" },
          ],
          blocks: [
            { id: "chooseMovie", label: "Chọn phim", correctZoneId: "inside" },
            { id: "chooseShowtime", label: "Chọn suất chiếu", correctZoneId: "inside" },
            { id: "chooseSeat", label: "Chọn ghế", correctZoneId: "inside" },
            { id: "payTicket", label: "Thanh toán vé", correctZoneId: "inside" },
            { id: "receiveTicket", label: "Nhận vé điện tử", correctZoneId: "inside" },
            {
              id: "queryMovies",
              label: "Query danh sách phim",
              correctZoneId: "exclude",
              feedback: "Đừng lo, ý này có liên quan, nhưng Query database nghĩa là truy vấn hoặc lấy dữ liệu từ cơ sở dữ liệu. Đây là xử lý bên trong hệ thống, không phải mục tiêu khách hàng nói ra.",
              simulation: "Khách hàng stickman đi tới 'Query danh sách phim' rồi dừng lại với dấu hỏi: 'Tôi không biết query database là gì. Tôi chỉ muốn chọn phim.'",
              visualEffect: "backendRoom",
            },
            {
              id: "callVnpay",
              label: "Gọi API VNPay",
              correctZoneId: "exclude",
              feedback: "Nhầm lẫn này rất phổ biến khi mới học Use Case. API là cách hệ thống giao tiếp với hệ thống khác. Use Case không nên gắn vào một cổng thanh toán cụ thể.",
              simulation: "Timeline đổi từ VNPay sang Momo. Block 'Gọi API VNPay' bị nứt: 'Cổng thanh toán đã đổi. Use Case gắn với VNPay bị lỗi thời.'",
              visualEffect: "outdatedTechnology",
            },
            {
              id: "renderTicket",
              label: "Render giao diện vé",
              correctZoneId: "exclude",
              feedback: "Render giao diện nghĩa là vẽ hoặc hiển thị màn hình cho người dùng. Đây là chi tiết UI. Mục tiêu của khách hàng là nhận hoặc xem được vé điện tử.",
              simulation: "Màn hình loading UI hiện lên rất đẹp, nhưng khách hàng vẫn đứng chờ: 'Tôi thấy màn hình rồi, nhưng vé của tôi đâu?'",
              visualEffect: "uiChanged",
            },
            {
              id: "lockSeat",
              label: "Khóa ghế tạm thời",
              correctZoneId: "exclude",
              feedback: "Gần đúng, nhưng đây mới là cơ chế hỗ trợ, chưa phải mục tiêu chính. Từ góc nhìn Actor, mục tiêu gần hơn là Chọn ghế.",
              simulation: "Một ghế bị khóa trong 5 phút. Khách hàng nhìn đồng hồ rồi hỏi: 'Vậy tôi đã chọn ghế xong chưa?'",
              visualEffect: "lockedSeat",
            },
            {
              id: "saveTicket",
              label: "Lưu vé vào database",
              correctZoneId: "exclude",
              feedback: "Database là nơi lưu dữ liệu. Việc lưu vé rất cần cho hệ thống, nhưng Use Case nên nói giá trị khách hàng nhận được: Nhận vé điện tử.",
              simulation: "Database sáng lên màu xanh, nhưng khách hàng vẫn đứng chờ ở quầy: 'Dữ liệu đã lưu rồi, còn vé của tôi?'",
              visualEffect: "backendRoom",
            },
          ],
          scenario: ["Khách hàng", "Chọn phim", "Chọn suất chiếu", "Chọn ghế", "Thanh toán vé", "Nhận vé điện tử"],
          successSimulation: "Khách hàng stickman đi trọn hành trình: Chọn phim -> Chọn suất chiếu -> Chọn ghế -> Thanh toán vé -> Nhận vé điện tử. Cuối đường, vé điện tử bật lên cùng mặt cười.",
          successVisualEffect: "successPath",
        },
      },
      {
        id: "what-02",
        title: "Mục tiêu chính hay chỉ là một đoạn đường?",
        story: "Khách hàng nói: 'Tôi muốn đặt được vé xem phim cho tối nay.' Hãy chọn tên Use Case phù hợp nhất cho toàn bộ mục tiêu này.",
        instruction: "Chọn một tên Use Case rồi bấm Run.",
        type: "SELECT_BLOCK_AND_RUN",
        data: {
          correctId: "bookTicket",
          blocks: [
            { id: "viewSchedule", label: "Xem lịch chiếu" },
            { id: "checkSeats", label: "Kiểm tra ghế trống" },
            { id: "bookTicket", label: "Đặt vé xem phim" },
            { id: "payTicket", label: "Thanh toán vé" },
            { id: "receiveTicket", label: "Nhận vé điện tử" },
          ],
          feedbackByBlock: {
            viewSchedule: fb("Gần đúng, nhưng đây mới là một bước hỗ trợ, chưa bao quát mục tiêu đặt vé.", "Khách hàng xem được lịch chiếu rồi đứng lại: 'Hay rồi, nhưng tôi vẫn chưa có vé.'", "stopAtNode"),
            checkSeats: fb("Không sai tuyệt đối. Nhưng trong tình huống đặt vé, nó là bước hỗ trợ cho Chọn ghế hoặc Đặt vé.", "Sơ đồ ghế hiện vài ghế xanh đỏ. Khách hàng nhìn xong nói: 'Tôi biết còn ghế, nhưng tôi vẫn chưa đặt vé.'", "bounceBack"),
            bookTicket: fb("Đúng. Đây là mục tiêu bao quát của Actor: khách hàng muốn hệ thống giúp mình đặt được vé xem phim.", "Khách hàng đi đủ hành trình và nhận vé điện tử. Tuyệt, mục tiêu chính đã được gọi đúng tên.", "successPath"),
            payTicket: fb("Thanh toán vé là Use Case quan trọng, nhưng chưa phải mục tiêu bao quát của toàn bộ hành trình này.", "Máy POS hiện ra ngay lập tức, nhưng khách hàng ngập ngừng: 'Tôi thanh toán cho phim nào, suất nào, ghế nào?'", "stopAtNode"),
            receiveTicket: fb("Đây là kết quả cuối hoặc hậu điều kiện. Nó có liên quan, nhưng chưa nhất thiết là Use Case chính cho toàn bộ mục tiêu đặt vé.", "Vé điện tử hiện ra rồi hệ thống báo đỏ: 'Không thể nhận vé nếu chưa đặt và thanh toán.'", "bounceBack"),
          },
        },
      },
      {
        id: "what-03",
        title: "Tên nào sống sót khi công nghệ thay đổi?",
        story: "Rạp phim thay đổi công nghệ thanh toán qua từng phiên bản. Version 1: VNPay. Version 2: Momo. Version 3: Ví nội bộ của rạp.",
        instruction: "Chọn tên Use Case vẫn đúng qua cả 3 phiên bản.",
        type: "SELECT_BLOCK_AND_RUN",
        data: {
          correctId: "payTicket",
          blocks: [
            { id: "callVnpay", label: "Gọi API VNPay" },
            { id: "callMomo", label: "Gọi API Momo" },
            { id: "payTicket", label: "Thanh toán vé" },
            { id: "verifyCallback", label: "Xác thực callback VNPay" },
            { id: "saveTransaction", label: "Lưu transactionId" },
          ],
          feedbackByBlock: {
            callVnpay: fb("Bạn đang gắn Use Case với một công nghệ cụ thể. API là cách hai hệ thống giao tiếp, không phải mục tiêu của Actor.", "Timeline chạy Version 1 VNPay ổn, sang Version 2 Momo thì block 'Gọi API VNPay' vỡ ra: 'VNPay đã bị thay bằng Momo.'", "outdatedTechnology"),
            callMomo: fb("Cũng gần giống lỗi VNPay: tên này sống theo công nghệ hiện tại, không sống theo mục tiêu người dùng.", "Timeline chạy tới Version 3 ví nội bộ của rạp. Block 'Gọi API Momo' bị nứt: 'Momo đã bị thay bằng ví nội bộ.'", "outdatedTechnology"),
            payTicket: fb("Đúng. Công nghệ đổi, mục tiêu người dùng vẫn giữ nguyên.", "Timeline VNPay -> Momo -> Ví nội bộ chạy qua cả 3 version. Block 'Thanh toán vé' vẫn sáng xanh.", "successPath"),
            verifyCallback: fb("Bạn đang nhìn từ góc độ developer. Callback thanh toán là tín hiệu cổng thanh toán gửi ngược về hệ thống; đây là cơ chế kỹ thuật, không phải mục tiêu Actor.", "Màn hình chuyển sang log backend, khách hàng biến mất khỏi cảnh. Dòng log chạy liên tục nhưng không ai thấy mục tiêu đặt vé.", "backendRoom"),
            saveTransaction: fb("Đây là lưu trữ kỹ thuật. transactionId là mã giao dịch để hệ thống theo dõi thanh toán, không phải điều khách hàng muốn đạt được.", "Database hiện lên, một dòng transactionId sáng xanh. Khách hàng đứng bên ngoài hỏi: 'Vé của tôi đâu?'", "backendRoom"),
          },
        },
      },
      {
        id: "what-04",
        title: "Khi Use Case Diagram biến thành flowchart",
        story: "Một bạn vẽ sơ đồ quá chi tiết cho quy trình đặt vé. Hãy chọn các block nên giữ ở mức Use Case, và loại các bước khiến sơ đồ biến thành flowchart.",
        type: "SORT_BLOCKS",
        data: {
          zones: [
            { id: "keep", label: "Giữ làm Use Case" },
            { id: "flowchart", label: "Quá chi tiết / biến sơ đồ thành flowchart" },
          ],
          blocks: [
            { id: "chooseMovie", label: "Chọn phim", correctZoneId: "keep" },
            { id: "chooseShowtime", label: "Chọn suất chiếu", correctZoneId: "keep" },
            { id: "chooseSeat", label: "Chọn ghế", correctZoneId: "keep" },
            { id: "ticketQuantity", label: "Nhập số lượng vé", correctZoneId: "flowchart", feedback: "Gần đúng vì nó nằm trong hành trình, nhưng tên này quá nhỏ. Nó làm Use Case Diagram bắt đầu giống từng bước thao tác.", simulation: "Sơ đồ thêm một node nhỏ. Stickman đi qua được một đoạn rồi phải dừng ở chi tiết nhập số lượng, scope meter tăng lên.", visualEffect: "flowchartWarning" },
            { id: "continueButton", label: "Bấm nút Tiếp tục", correctZoneId: "flowchart", feedback: "Đây là thao tác UI. Nếu nút đổi thành vuốt, auto-next hoặc giọng nói, mục tiêu người dùng vẫn không đổi.", simulation: "Nút Tiếp tục phóng to chiếm canvas. Stickman bấm nút nhưng sơ đồ không nói rõ khách hàng đạt được giá trị gì.", visualEffect: "flowchartWarning" },
            { id: "checkSeat", label: "Kiểm tra ghế trống", correctZoneId: "flowchart", feedback: "Không sai tuyệt đối, nhưng trong ngữ cảnh này nó là bước hỗ trợ cho Chọn ghế, chưa phải mục tiêu chính của sơ đồ.", simulation: "Sơ đồ ghế xanh đỏ hiện ra, rồi hành trình kẹt giữa kiểm tra và chọn. Cảnh báo: 'Bạn đang mô tả đoạn đường, chưa phải đích đến.'", visualEffect: "bounceBack" },
            { id: "lockSeat", label: "Khóa ghế 5 phút", correctZoneId: "flowchart", feedback: "Đây là cơ chế hỗ trợ bên trong hệ thống. Use Case Diagram không nên mô tả từng xử lý nhỏ như giữ ghế tạm thời.", simulation: "Đồng hồ 5 phút xuất hiện, node chen vào giữa đường. Complexity meter nhảy lên và sơ đồ phình ra.", visualEffect: "flowchartWarning" },
            { id: "payTicket", label: "Thanh toán vé", correctZoneId: "keep" },
            { id: "receiveTicket", label: "Nhận vé điện tử", correctZoneId: "keep" },
          ],
          successSimulation: "Sơ đồ gọn lại thành 5 mục tiêu chính: Chọn phim, Chọn suất chiếu, Chọn ghế, Thanh toán vé, Nhận vé điện tử. Người đọc hiểu hệ thống giúp khách hàng làm gì mà không bị chìm trong từng click.",
          successVisualEffect: "successPath",
          mixedSimulation: "Sơ đồ phình ra, node chen chúc, stickman phải đi quá nhiều bước. Cảnh báo: Use Case Diagram nên mô tả mục tiêu, không mô tả từng click hoặc từng xử lý nhỏ.",
          mixedVisualEffect: "flowchartWarning",
        },
      },
      {
        id: "what-05",
        title: "Đổi Actor, đổi mục tiêu",
        story: "Trong cùng một Cinema Booking System, mỗi Actor tương tác với hệ thống vì một mục tiêu khác nhau. Hãy giữ lại các association thể hiện mục tiêu đúng, và loại bỏ các đường nối chỉ mô tả thao tác hoặc kỹ thuật.",
        instruction: "Chọn một Actor rồi chọn Use Case phù hợp để tạo đường nối. Chỉ nối các mục tiêu đúng, không nối các thao tác kỹ thuật.",
        type: "CONNECT_ACTOR_TO_USECASE",
        data: {
          actors: [
            { id: "customer", label: "Khách hàng", kind: "human" },
            { id: "staff", label: "Nhân viên rạp", kind: "human" },
            { id: "paymentGateway", label: "Cổng thanh toán", kind: "system" },
          ],
          useCases: [
            { id: "bookTicket", label: "Đặt vé xem phim" },
            { id: "confirmTicket", label: "Xác nhận vé tại rạp" },
            { id: "confirmPayment", label: "Xác nhận kết quả thanh toán" },
            { id: "scanQr", label: "Quét mã QR vé" },
            { id: "paymentCallback", label: "Gọi callback thanh toán" },
          ],
          correctConnections: [c("customer", "bookTicket"), c("staff", "confirmTicket"), c("paymentGateway", "confirmPayment")],
          feedbackByConnection: {
            "customer->confirmPayment": fb("Bạn đang nhìn nhầm lens của Actor. Khách hàng không cần xác thực log thanh toán; họ muốn biết mình đã mua vé được chưa.", "Khách hàng nhìn màn hình log thanh toán và bối rối: 'Tôi chỉ muốn biết mình đã mua vé được chưa.'", "backendRoom"),
            "customer->scanQr": fb("Khách hàng có thể xuất trình mã QR, nhưng mục tiêu của khách hàng không phải là quét mã. Việc xác nhận vé tại cổng thường thuộc về Nhân viên rạp. Use Case ổn định hơn là Xác nhận vé tại rạp.", "Khách hàng đưa mã QR ra, nhưng người thực hiện xác nhận ở cổng là nhân viên rạp. Nếu rạp đổi QR sang NFC, mục tiêu xác nhận vé vẫn giữ nguyên.", "outdatedTechnology"),
            "staff->scanQr": fb("Quét QR là cách làm hiện tại. Nếu sau này rạp dùng NFC hoặc mã số vé, Use Case nên vẫn là Xác nhận vé tại rạp.", "Máy quét QR đổi thành cổng NFC. Block 'Quét mã QR vé' bị đánh dấu lỗi thời, còn mục tiêu xác nhận vé vẫn sống tiếp.", "outdatedTechnology"),
            "paymentGateway->paymentCallback": fb("Callback thanh toán là cách cổng thanh toán gửi kết quả về hệ thống sau khi giao dịch hoàn tất. Đây là chi tiết giao tiếp kỹ thuật. Ở mức Use Case, ta nên mô tả mục tiêu là Xác nhận kết quả thanh toán.", "Màn hình hiện log API callback. Cổng thanh toán muốn báo kết quả, không muốn người đọc sơ đồ chìm trong protocol.", "backendRoom"),
          },
          successSimulation: "Đúng. Mỗi Actor đang được nối với mục tiêu phù hợp: Khách hàng đặt vé, Nhân viên rạp xác nhận vé, Cổng thanh toán xác nhận kết quả thanh toán.",
          successVisualEffect: "successPath",
        },
      },
      {
        id: "what-06",
        title: "Phòng cấp cứu Use Case",
        story: "Một sơ đồ Use Case bị nhiễm code, UI và database. Hãy cứu nó.",
        type: "SORT_BLOCKS",
        data: {
          zones: [
            { id: "keep", label: "Giữ lại" },
            { id: "rename", label: "Đổi tên" },
            { id: "remove", label: "Loại bỏ" },
          ],
          blocks: [
            { id: "bookTicket", label: "Đặt vé xem phim", correctZoneId: "keep", successFeedback: "Use Case tốt: nói bằng mục tiêu của khách hàng." },
            { id: "queryMovie", label: "Query bảng Movie", correctZoneId: "remove", feedback: "Query bảng Movie nghĩa là truy vấn dữ liệu từ bảng Movie trong database. Đây là chi tiết lưu trữ, nên đưa vào thùng Internal.", simulation: "Block database được chuyển vào thùng 'Internal'. Stickman không cần đi qua bảng dữ liệu để hiểu mục tiêu.", visualEffect: "backendRoom" },
            { id: "callVnpay", label: "Gọi API VNPay", correctZoneId: "remove", feedback: "API là cách hệ thống giao tiếp với hệ thống khác. Tên này phụ thuộc công nghệ và nên loại khỏi Use Case Diagram.", simulation: "Block API bị đưa vào thùng Internal. Timeline đổi sang ví khác nên block VNPay nứt nhẹ.", visualEffect: "outdatedTechnology" },
            { id: "scanQr", label: "Quét mã QR vé", correctZoneId: "rename", feedback: "Gần đúng, nhưng quá hẹp theo cách làm hiện tại. Đổi tên thành Xác nhận vé tại rạp để sống được cả khi đổi sang NFC.", simulation: "Block đi qua máy Rename và đổi thành 'Xác nhận vé tại rạp'.", visualEffect: "outdatedTechnology" },
            { id: "confirmTicket", label: "Xác nhận vé tại rạp", correctZoneId: "keep", successFeedback: "Use Case tốt: nói mục tiêu nghiệp vụ của nhân viên rạp." },
            { id: "renderQr", label: "Render QR code vé", correctZoneId: "remove", feedback: "Render QR code nghĩa là vẽ hoặc hiển thị mã QR. Đây là chi tiết UI/kỹ thuật, không phải mục tiêu Actor.", simulation: "Màn hình vẽ QR sáng lên nhưng sơ đồ bị nhiễu. Bác sĩ Use Case đưa nó vào thùng Internal.", visualEffect: "backendRoom" },
            { id: "viewTicket", label: "Xem vé đã đặt", correctZoneId: "keep", successFeedback: "Use Case tốt: khách hàng nhận được giá trị rõ ràng." },
            { id: "insertTicket", label: "Insert Ticket Record", correctZoneId: "remove", feedback: "Insert record nghĩa là lưu một dòng dữ liệu mới vào database. Đây là chi tiết lưu trữ bên trong hệ thống.", simulation: "Database sáng lên, nhưng Actor biến mất khỏi màn hình. Block được đưa vào thùng Internal.", visualEffect: "backendRoom" },
            { id: "checkSeat", label: "Kiểm tra ghế trống", correctZoneId: "rename", feedback: "Không sai tuyệt đối. Trong bài này, hãy đổi thành Xem tình trạng ghế hoặc Chọn ghế để diễn đạt mục tiêu người dùng rõ hơn.", simulation: "Block đi qua máy Rename: 'Kiểm tra ghế trống' đổi thành 'Xem tình trạng ghế' hoặc 'Chọn ghế'.", visualEffect: "renameMachine" },
            { id: "lockSeat", label: "Khóa ghế trong 5 phút", correctZoneId: "remove", feedback: "Đây là cơ chế hỗ trợ bên trong hệ thống, không phải mục tiêu độc lập của Actor.", simulation: "Đồng hồ 5 phút được kéo khỏi sơ đồ. Use Case tốt sáng xanh, chi tiết xử lý đi vào Internal.", visualEffect: "flowchartWarning" },
          ],
          successSimulation: "Sơ đồ sạch lại: Đặt vé xem phim, Xác nhận vé tại rạp, Xem vé đã đặt. Bây giờ sơ đồ nói bằng ngôn ngữ của Actor, không phải ngôn ngữ của code.",
          successVisualEffect: "successPath",
          mixedSimulation: "Phòng cấp cứu Use Case đang hoạt động: code/database vào thùng Internal, tên quá hẹp đi qua máy Rename, Use Case tốt sáng xanh.",
          mixedVisualEffect: "renameMachine",
        },
      },
      {
        id: "what-07",
        title: "Run Diagram: Khách hàng có nhận được vé không?",
        story: "Khách hàng muốn đặt vé xem phim online. Nếu Use Case Diagram đúng, hành trình sẽ đi được từ Actor Khách hàng đến mục tiêu cuối cùng là Nhận vé. Nếu bạn chọn nhầm thao tác kỹ thuật hoặc thiếu Use Case quan trọng, hành trình sẽ bị kẹt.",
        instruction: "Chọn các Use Case cần thiết cho hành trình đặt vé. Sau đó nối Actor Khách hàng với mục tiêu chính và bấm Run Diagram.",
        type: "RUN_DIAGRAM_SCENARIO",
        data: {
          mode: "useCaseRunSimulation",
          systemLabel: "Cinema Booking System",
          goalText: "Khách hàng muốn đặt vé xem phim và nhận được vé điện tử. Diagram pass khi hành trình đi đủ từ Actor Khách hàng qua các mục tiêu chính, không lẫn chi tiết triển khai.",
          idleGoal: "Mục tiêu kiểm thử: Khách hàng muốn đặt vé xem phim và nhận được vé.",
          passCondition: "Điều kiện pass: chọn đúng Use Case, không chọn block kỹ thuật, có mục tiêu cuối cùng Nhận vé.",
          actors: [{ id: "customer", label: "Khách hàng", kind: "human" }],
          useCases: [
            { id: "viewSchedule", label: "Xem lịch chiếu", icon: "Lịch" },
            { id: "bookTicket", label: "Đặt vé xem phim", icon: "Vé" },
            { id: "chooseSeat", label: "Chọn ghế", icon: "Ghế" },
            { id: "payTicket", label: "Thanh toán vé", icon: "Pay" },
            { id: "receiveTicket", label: "Nhận vé", icon: "QR" },
          ],
          journeySteps: [
            { id: "viewSchedule", label: "Xem lịch chiếu", icon: "Lịch" },
            { id: "bookTicket", label: "Đặt vé xem phim", icon: "Vé" },
            { id: "chooseSeat", label: "Chọn ghế", icon: "Ghế" },
            { id: "payTicket", label: "Thanh toán vé", icon: "Pay" },
            { id: "receiveTicket", label: "Nhận vé", icon: "QR" },
          ],
          distractors: [
            { id: "queryMovie", label: "Query bảng Movie", feedback: "Query bảng Movie là cách hệ thống lấy dữ liệu phim từ database. Block này có thể đúng ở thiết kế kỹ thuật hoặc sequence/activity diagram, nhưng không phù hợp trong Use Case Diagram.", suggestion: "Trong Use Case Diagram, hãy dùng Xem lịch chiếu hoặc Đặt vé xem phim tùy mục tiêu của Actor.", visualEffect: "backendRoom" },
            { id: "renderSeat", label: "Render giao diện ghế", feedback: "Render giao diện ghế là việc vẽ màn hình ghế cho người dùng. Block này có thể đúng ở thiết kế UI, nhưng không phù hợp trong Use Case Diagram.", suggestion: "Trong Use Case Diagram, hãy dùng Chọn ghế.", visualEffect: "uiChanged" },
            { id: "callVnpay", label: "Gọi API VNPay", feedback: "Gọi API VNPay là cách hệ thống xử lý thanh toán bên trong, không phải mục tiêu mà khách hàng trực tiếp thực hiện. Block này có thể đúng ở thiết kế kỹ thuật hoặc sequence/activity diagram, nhưng không phù hợp trong Use Case Diagram.", suggestion: "Trong Use Case Diagram, hãy dùng Thanh toán vé.", visualEffect: "outdatedTechnology" },
            { id: "lockSeat", label: "Khóa ghế trong 5 phút", feedback: "Khóa ghế trong 5 phút là cơ chế giữ chỗ tạm thời bên trong hệ thống. Block này có thể đúng ở thiết kế kỹ thuật hoặc activity diagram, nhưng không phù hợp trong Use Case Diagram.", suggestion: "Trong Use Case Diagram, hãy dùng Chọn ghế.", visualEffect: "flowchartWarning" },
            { id: "insertTicket", label: "Insert Ticket Record", feedback: "Insert Ticket Record là thao tác lưu một dòng dữ liệu mới vào database. Block này có thể đúng ở thiết kế kỹ thuật, nhưng không phù hợp trong Use Case Diagram.", suggestion: "Trong Use Case Diagram, hãy dùng Nhận vé.", visualEffect: "backendRoom" },
          ],
          correctConnections: [
            c("customer", "viewSchedule"),
            c("customer", "bookTicket"),
            c("customer", "chooseSeat"),
            c("customer", "payTicket"),
            c("customer", "receiveTicket"),
          ],
          missingFeedback: {
            payTicket: {
              feedbackBody: "❌ Khách hàng đã chọn ghế nhưng chưa thể hoàn tất đặt vé.",
              suggestion: "Hành trình còn thiếu Use Case Thanh toán vé. Nếu thiếu bước tạo giá trị chính, actor không thể đạt được mục tiêu cuối cùng.",
            },
            receiveTicket: {
              feedbackBody: "❌ Thanh toán xong nhưng khách hàng chưa nhận được vé.",
              suggestion: "Use Case Diagram còn thiếu mục tiêu cuối cùng: Nhận vé. Một Use Case tốt phải thể hiện kết quả có giá trị với actor.",
            },
          },
          scenarios: [
            {
              id: "bookingJourney",
              title: "Khách hàng nhận vé",
              path: ["Khách hàng", "Xem lịch chiếu", "Đặt vé xem phim", "Chọn ghế", "Thanh toán vé", "Nhận vé"],
              requiredActors: ["customer"],
              requiredUseCases: ["viewSchedule", "bookTicket", "chooseSeat", "payTicket", "receiveTicket"],
              requiredConnections: [c("customer", "viewSchedule"), c("customer", "bookTicket"), c("customer", "chooseSeat"), c("customer", "payTicket"), c("customer", "receiveTicket")],
              feedback: fb("Hành trình chưa đủ để khách hàng nhận được vé. Kiểm tra lại các mục tiêu lõi: xem lịch, đặt vé, chọn ghế, thanh toán và nhận vé.", "Run customer journey bị đứt giữa đường. Khách hàng chưa thể đi tới vé điện tử.", "stopAtNode"),
            },
          ],
          successSimulation: "✅ Khách hàng đã nhận được vé! Diagram của bạn tập trung vào mục tiêu người dùng: xem lịch chiếu, đặt vé, chọn ghế, thanh toán và nhận vé.",
          successVisualEffect: "ticketSuccess",
        },
      },
      {
        id: "what-08",
        title: "Insight Fill",
        type: "INSIGHT",
        data: {
          text: "Khi xác định Use Case, hãy bắt đầu từ ______ mà Actor muốn đạt được. Use Case nên nói bằng ngôn ngữ của ______, không phải ngôn ngữ của code. Một Use Case tốt mô tả ______ người dùng nhận được, không mô tả từng ______, giao diện, database hay API.",
          answers: ["mục tiêu", "Actor", "giá trị", "bước xử lý"],
          finalInsight: "Khi xác định Use Case, hãy bắt đầu từ mục tiêu mà Actor muốn đạt được. Use Case nên nói bằng ngôn ngữ của Actor, không phải ngôn ngữ của code. Một Use Case tốt mô tả giá trị người dùng nhận được, không mô tả từng bước xử lý, giao diện, database hay API.",
          mantra: "Use Case trả lời câu hỏi: Hệ thống giúp Actor đạt được điều gì? Không trả lời: Hệ thống xử lý bên trong như thế nào?",
        },
      },
    ],
  },
  {
    id: "system-boundary",
    title: "Bài 2: System Boundary",
    description: "Use Case nằm trong boundary; Actor và external system đứng ngoài.",
    steps: [
      {
        id: "boundary-01",
        title: "Online Clothing Store Boundary",
        story: "Bạn đang xây dựng app bán quần áo online. Thứ nằm trong hộp là phần team chịu trách nhiệm như chức năng chính.",
        type: "DRAG_TO_BOUNDARY",
        data: {
          boundaryLabel: "Online Clothing Store App",
          zones: [
            { id: "inside", label: "Trong System Boundary" },
            { id: "outside", label: "Ngoài System Boundary" },
            { id: "exclude", label: "Không đưa vào Use Case Diagram" },
          ],
          blocks: [
            { id: "customer", label: "Khách hàng", correctZoneId: "outside", feedback: "Khách hàng là Actor." },
            { id: "view", label: "Xem sản phẩm", correctZoneId: "inside" },
            { id: "cart", label: "Thêm vào giỏ hàng", correctZoneId: "inside" },
            { id: "pay", label: "Thanh toán đơn hàng", correctZoneId: "inside" },
            { id: "zalo", label: "ZaloPay", correctZoneId: "outside", feedback: "ZaloPay là external system." },
            { id: "shipper", label: "Đơn vị vận chuyển", correctZoneId: "outside" },
            { id: "db", label: "Database sản phẩm", correctZoneId: "exclude", feedback: "Database thuộc thiết kế kỹ thuật, không cần vẽ trong Use Case Diagram." },
          ],
          successSimulation: "Scope rõ ràng: hệ thống chứa chức năng, bên ngoài là actor và hệ thống phụ trợ.",
        },
      },
      {
        id: "boundary-02",
        title: "Boundary Resize Simulation",
        instruction: "Sửa để Actor ở ngoài, Use Case ở trong, external system ở ngoài, database bị loại khỏi sơ đồ.",
        type: "DRAG_TO_BOUNDARY",
        data: {
          boundaryLabel: "Scope Meter",
          zones: [
            { id: "inside", label: "Trong Boundary" },
            { id: "outside", label: "Ngoài Boundary" },
            { id: "exclude", label: "Không đưa vào sơ đồ" },
          ],
          blocks: [
            { id: "actor", label: "Khách hàng", correctZoneId: "outside", penalty: "Scope +20%" },
            { id: "uc", label: "Xem sản phẩm", correctZoneId: "inside" },
            { id: "payment", label: "Cổng thanh toán", correctZoneId: "outside", penalty: "Scope +50%" },
            { id: "database", label: "Database sản phẩm", correctZoneId: "exclude", penalty: "Complexity +30%" },
          ],
          initialPlacements: { actor: "inside", uc: "outside", payment: "inside", database: "inside" },
          successSimulation: "Scope meter ổn định: team không vô tình nhận xây cả actor, cổng thanh toán hay database design trong sơ đồ.",
        },
      },
      {
        id: "boundary-03",
        title: "FPTU Club Boundary",
        type: "DRAG_TO_BOUNDARY",
        data: {
          boundaryLabel: "FPTU Club Management System",
          zones: [
            { id: "inside", label: "Trong Boundary" },
            { id: "outside", label: "Ngoài Boundary" },
            { id: "exclude", label: "Không đưa vào sơ đồ" },
          ],
          blocks: [
            { id: "student", label: "Sinh viên", correctZoneId: "outside" },
            { id: "admin", label: "Admin", correctZoneId: "outside" },
            { id: "list", label: "Xem danh sách CLB", correctZoneId: "inside" },
            { id: "search", label: "Tìm kiếm thông tin CLB", correctZoneId: "inside" },
            { id: "approve", label: "Duyệt thông tin CLB", correctZoneId: "inside" },
            { id: "google", label: "Google Login", correctZoneId: "outside" },
            { id: "email", label: "Email Service", correctZoneId: "outside" },
            { id: "table", label: "Club Table", correctZoneId: "exclude" },
          ],
          successSimulation: "FPTU Club System đã có ranh giới trách nhiệm rõ.",
        },
      },
      {
        id: "boundary-04",
        title: "Fix Broken Diagram",
        type: "DRAG_TO_BOUNDARY",
        data: {
          boundaryLabel: "Broken FPTU Club Diagram",
          zones: [
            { id: "inside", label: "Trong Boundary" },
            { id: "outside", label: "Ngoài Boundary" },
            { id: "exclude", label: "Không đưa vào sơ đồ" },
          ],
          blocks: [
            { id: "student", label: "Sinh viên", correctZoneId: "outside" },
            { id: "admin", label: "Admin", correctZoneId: "outside" },
            { id: "list", label: "Xem danh sách CLB", correctZoneId: "inside" },
            { id: "google", label: "Google Login", correctZoneId: "outside" },
            { id: "table", label: "Club Table", correctZoneId: "exclude" },
            { id: "search", label: "Tìm kiếm thông tin CLB", correctZoneId: "inside" },
          ],
          initialPlacements: { student: "inside", admin: "inside", list: "inside", google: "inside", table: "inside", search: "outside" },
          successSimulation: "Sơ đồ được sửa: actor và Google Login ra ngoài, table biến mất, Use Case vào trong.",
        },
      },
      {
        id: "boundary-05",
        title: "Boundary Stress Test",
        type: "RUN_DIAGRAM_SCENARIO",
        data: {
          systemLabel: "FPTU Club Management System",
          actors: [
            { id: "student", label: "Sinh viên", kind: "human" },
            { id: "admin", label: "Admin", kind: "human" },
            { id: "email", label: "Email Service", kind: "system" },
          ],
          useCases: [
            { id: "search", label: "Tìm kiếm thông tin CLB" },
            { id: "approve", label: "Duyệt thông tin CLB" },
            { id: "send", label: "Gửi email xác nhận" },
          ],
          correctConnections: [c("student", "search"), c("admin", "approve"), c("email", "send")],
          scenarios: [
            { id: "s1", title: "Sinh viên muốn tìm CLB", path: ["Sinh viên", "Tìm kiếm thông tin CLB"], requiredActors: ["student"], requiredUseCases: ["search"], requiredConnections: [c("student", "search")], feedback: "Cần Sinh viên ngoài boundary và Tìm kiếm thông tin CLB trong boundary." },
            { id: "s2", title: "Admin muốn duyệt thông tin CLB", path: ["Admin", "Duyệt thông tin CLB"], requiredActors: ["admin"], requiredUseCases: ["approve"], requiredConnections: [c("admin", "approve")], feedback: "Cần Admin nối đúng với use case duyệt." },
            { id: "s3", title: "Hệ thống gửi email xác nhận", path: ["Email Service", "Gửi email xác nhận"], requiredActors: ["email"], requiredUseCases: ["send"], requiredConnections: [c("email", "send")], feedback: "Email Service là external actor đứng ngoài boundary." },
          ],
          successSimulation: "Ba scenario đều chạy qua boundary đúng.",
        },
      },
      {
        id: "boundary-06",
        title: "Insight",
        type: "INSIGHT",
        data: {
          text: "Actor ở ______. Use Case ở ______. External system cũng ở ______. Database không cần vẽ trong Use Case Diagram.",
          answers: ["ngoài", "trong", "ngoài"],
          finalInsight: "Actor ở ngoài. Use Case ở trong. External system cũng ở ngoài. Database không cần vẽ trong Use Case Diagram.",
        },
      },
    ],
  },
  {
    id: "actor",
    title: "Bài 3: Actor không chỉ là con người",
    description: "Actor là vai trò, external system hoặc thời gian kích hoạt hệ thống.",
    steps: [
      {
        id: "actor-01",
        title: "Auto Cleanup Actor",
        story: "Cứ 00:00 mỗi ngày, hệ thống tự động xóa các đơn hàng nháp bị bỏ quên.",
        type: "CONNECT_ACTOR_TO_USECASE",
        data: {
          actors: [
            { id: "customer", label: "Khách hàng", kind: "human" },
            { id: "admin", label: "Quản trị viên", kind: "human" },
            { id: "time", label: "Thời gian: 00:00 mỗi ngày", kind: "time" },
          ],
          useCases: [{ id: "cleanup", label: "Tự động dọn dẹp đơn hàng nháp" }],
          correctConnections: [c("time", "cleanup")],
          feedbackByConnection: {
            "customer->cleanup": "Khách hàng sai vì họ không phải thức đêm để bấm nút.",
            "admin->cleanup": "Quản trị viên sai vì chức năng tự động bị biến thành thủ công.",
            "time->cleanup": "Thời gian đúng vì nó kích hoạt chức năng tự động.",
          },
          successSimulation: "00:00 tới, hệ thống tự kích hoạt cleanup mà không cần người bấm.",
        },
      },
      {
        id: "actor-02",
        title: "Actor Type Sorting",
        type: "SORT_BLOCKS",
        data: {
          zones: [
            { id: "human", label: "Human Actor" },
            { id: "system", label: "External System Actor" },
            { id: "time", label: "Time Actor" },
          ],
          blocks: [
            { id: "student", label: "Sinh viên", correctZoneId: "human" },
            { id: "admin", label: "Admin", correctZoneId: "human" },
            { id: "club", label: "Ban chủ nhiệm", correctZoneId: "human" },
            { id: "payment", label: "Cổng thanh toán", correctZoneId: "system" },
            { id: "google", label: "Google Login", correctZoneId: "system" },
            { id: "email", label: "Email Service", correctZoneId: "system" },
            { id: "midnight", label: "00:00 mỗi ngày", correctZoneId: "time" },
            { id: "month", label: "Cuối mỗi tháng", correctZoneId: "time" },
          ],
          successSimulation: "Actor không chỉ là người: hệ thống ngoài và thời gian cũng có thể kích hoạt Use Case.",
        },
      },
      {
        id: "actor-03",
        title: "Actor or Use Case",
        type: "SORT_BLOCKS",
        data: {
          zones: [
            { id: "actor", label: "Actor" },
            { id: "usecase", label: "Use Case" },
          ],
          blocks: [
            { id: "student", label: "Sinh viên", correctZoneId: "actor" },
            { id: "list", label: "Xem danh sách CLB", correctZoneId: "usecase" },
            { id: "search", label: "Tìm kiếm thông tin CLB", correctZoneId: "usecase" },
            { id: "admin", label: "Admin", correctZoneId: "actor" },
            { id: "approve", label: "Duyệt thông tin CLB", correctZoneId: "usecase" },
            { id: "mail", label: "Cổng email", correctZoneId: "actor" },
            { id: "send", label: "Gửi email nhắc lịch", correctZoneId: "usecase" },
            { id: "time", label: "7:00 mỗi ngày", correctZoneId: "actor" },
          ],
          successSimulation: "Danh từ vai trò đứng ngoài; cụm động từ mục tiêu nằm trong boundary.",
        },
      },
      {
        id: "actor-04",
        title: "Role, Not Person",
        story: "Nam là sinh viên FPTU và cũng là thành viên Ban chủ nhiệm CLB Guitar.",
        type: "SORT_BLOCKS",
        data: {
          zones: [
            { id: "draw", label: "Nên vẽ làm Actor" },
            { id: "skip", label: "Không nên vẽ làm Actor" },
          ],
          blocks: [
            { id: "nam", label: "Nam", correctZoneId: "skip" },
            { id: "student", label: "Sinh viên", correctZoneId: "draw" },
            { id: "club", label: "Ban chủ nhiệm", correctZoneId: "draw" },
            { id: "shirt", label: "Người mặc áo xanh", correctZoneId: "skip" },
          ],
          successSimulation: "Use Case Diagram vẽ vai trò, không vẽ cá nhân cụ thể.",
        },
      },
      {
        id: "actor-05",
        title: "Connect Actor to Goal",
        type: "CONNECT_ACTOR_TO_USECASE",
        data: {
          actors: [
            { id: "student", label: "Sinh viên" },
            { id: "member", label: "Thành viên CLB" },
            { id: "lead", label: "Ban chủ nhiệm" },
            { id: "admin", label: "Admin" },
            { id: "time", label: "7:00 mỗi ngày" },
            { id: "email", label: "Email Service" },
          ],
          useCases: [
            { id: "list", label: "Xem danh sách CLB" },
            { id: "internal", label: "Xem hoạt động nội bộ" },
            { id: "event", label: "Tạo sự kiện" },
            { id: "approve", label: "Duyệt thông tin CLB" },
            { id: "send", label: "Gửi email nhắc lịch họp" },
          ],
          correctConnections: [c("student", "list"), c("member", "internal"), c("lead", "event"), c("admin", "approve"), c("time", "send"), c("email", "send")],
          feedbackByConnection: {
            "student->approve": "Sai quyền: Sinh viên không duyệt thông tin CLB.",
            "email->event": "Sai: Email Service chỉ hỗ trợ gửi thông báo.",
          },
          successSimulation: "Mỗi actor nối với mục tiêu mà vai trò đó thật sự kích hoạt hoặc hỗ trợ.",
        },
      },
      {
        id: "actor-06",
        title: "Insight",
        type: "INSIGHT",
        data: {
          text: "Actor là thực thể đứng ______ hệ thống, có thể ______ hoặc ______ hệ thống.",
          answers: ["ngoài", "tương tác với", "kích hoạt"],
          finalInsight: "Actor là thực thể đứng ngoài hệ thống, có thể tương tác với hoặc kích hoạt hệ thống.",
        },
      },
    ],
  },
  {
    id: "naming",
    title: "Bài 4: Quy tắc đặt tên Use Case",
    description: "Tên tốt thường là động từ nghiệp vụ + đối tượng nghiệp vụ.",
    steps: [
      {
        id: "name-01",
        title: "Build Use Case Name",
        story: "Người dùng muốn thay đổi địa chỉ giao hàng trong tài khoản.",
        type: "BUILD_USECASE_NAME",
        data: {
          verbs: [
            { id: "update", label: "Cập nhật" },
            { id: "manage", label: "Quản lý" },
            { id: "click", label: "Nhấp chuột" },
            { id: "api", label: "Gọi API" },
          ],
          nouns: [
            { id: "address", label: "địa chỉ giao hàng" },
            { id: "form", label: "form thông tin" },
            { id: "db", label: "database user" },
            { id: "profile", label: "hồ sơ cá nhân" },
          ],
          acceptedPairs: [c("update", "address")],
          feedbackByPair: {
            "click->form": "Sai vì phụ thuộc UI.",
            "api->db": "Sai vì là kỹ thuật.",
            "manage->profile": "Quá rộng trong tình huống này.",
            "update->address": "Rõ mục tiêu nghiệp vụ.",
          },
          successSimulation: "Tên oval rõ hành động và đối tượng nghiệp vụ: Cập nhật địa chỉ giao hàng.",
        },
      },
      {
        id: "name-02",
        title: "Rename Broken Use Cases",
        type: "SORT_BLOCKS",
        data: {
          zones: [
            { id: "actor", label: "Đưa ra ngoài làm Actor" },
            { id: "rename", label: "Cần đổi thành Use Case tốt" },
            { id: "keep", label: "Giữ nguyên" },
          ],
          blocks: [
            { id: "student", label: "Student", correctZoneId: "actor" },
            { id: "screen", label: "Club List Screen", correctZoneId: "rename", feedback: "Đổi thành Xem danh sách CLB." },
            { id: "click", label: "Click Search Button", correctZoneId: "rename", feedback: "Đổi thành Tìm kiếm thông tin CLB." },
            { id: "controller", label: "SearchClubController", correctZoneId: "rename", feedback: "Đổi thành Tìm kiếm thông tin CLB." },
            { id: "insert", label: "Insert Club Table", correctZoneId: "rename", feedback: "Đổi thành Tạo hoặc Cập nhật thông tin CLB." },
            { id: "list", label: "Xem danh sách CLB", correctZoneId: "keep" },
            { id: "search", label: "Tìm kiếm thông tin CLB", correctZoneId: "keep" },
          ],
          successSimulation: "Tên bị hỏng đã được phân loại: actor ra ngoài, UI/code/database được đổi thành mục tiêu nghiệp vụ.",
        },
      },
      {
        id: "name-03",
        title: "Naming Error Detector",
        type: "SORT_BLOCKS",
        data: {
          zones: [
            { id: "actor", label: "Actor Name" },
            { id: "ui", label: "UI Detail" },
            { id: "code", label: "Code Detail" },
            { id: "db", label: "Database Detail" },
            { id: "good", label: "Good Use Case Name" },
          ],
          blocks: [
            { id: "admin", label: "Admin", correctZoneId: "actor" },
            { id: "button", label: "Button Login", correctZoneId: "ui" },
            { id: "auth", label: "AuthController", correctZoneId: "code" },
            { id: "insert", label: "Insert User Table", correctZoneId: "db" },
            { id: "login", label: "Đăng nhập", correctZoneId: "good" },
            { id: "create", label: "Tạo tài khoản", correctZoneId: "good" },
            { id: "render", label: "Render Profile Page", correctZoneId: "ui" },
            { id: "update", label: "Cập nhật thông tin cá nhân", correctZoneId: "good" },
          ],
          successSimulation: "Bộ lọc tên hoạt động: chỉ cụm mục tiêu nghiệp vụ được giữ làm Use Case.",
        },
      },
      {
        id: "name-04",
        title: "Verb Strength Challenge",
        story: "Admin kiểm tra thông tin CLB trước khi cho hiển thị công khai.",
        type: "SELECT_BLOCK_AND_RUN",
        data: {
          correctId: "approve",
          blocks: [
            { id: "manage", label: "Quản lý CLB" },
            { id: "process", label: "Xử lý thông tin CLB" },
            { id: "approve", label: "Duyệt thông tin CLB" },
          ],
          feedbackByBlock: {
            manage: fb("Quá rộng."),
            process: fb("Mơ hồ."),
            approve: fb("Rõ hành động và mục tiêu."),
          },
        },
      },
      {
        id: "name-05",
        title: "Build Names for FPTU Club System",
        type: "BUILD_USECASE_NAME",
        data: {
          verbs: [
            { id: "view", label: "Xem" },
            { id: "search", label: "Tìm kiếm" },
            { id: "create", label: "Tạo" },
            { id: "approve", label: "Duyệt" },
            { id: "send", label: "Gửi" },
            { id: "update", label: "Cập nhật" },
          ],
          nouns: [
            { id: "list", label: "danh sách CLB" },
            { id: "info", label: "thông tin CLB" },
            { id: "event", label: "sự kiện" },
            { id: "notice", label: "thông báo" },
            { id: "join", label: "yêu cầu tham gia CLB" },
            { id: "internal", label: "hoạt động nội bộ" },
          ],
          acceptedPairs: [c("view", "list"), c("search", "info"), c("create", "event"), c("approve", "info"), c("send", "notice"), c("update", "info"), c("view", "internal")],
          requiredCount: 5,
          successSimulation: "Bạn đã tạo được một bộ tên Use Case đủ dùng cho FPTU Club System.",
        },
      },
      {
        id: "name-06",
        title: "Insight",
        type: "INSIGHT",
        data: {
          text: "Tên Use Case tốt nên là ______ + ______, tránh UI, code, database và API.",
          answers: ["động từ nghiệp vụ", "đối tượng nghiệp vụ"],
          finalInsight: "Tên Use Case tốt nên là động từ nghiệp vụ + đối tượng nghiệp vụ, tránh UI, code, database và API.",
        },
      },
    ],
  },
  {
    id: "mini-project",
    title: "Mini Project: Build Your First Use Case Diagram",
    description: "Xây sơ đồ Use Case đầu tiên cho Online Car Rental Management System.",
    steps: [
      {
        id: "project-00",
        title: "Phân tích Requirement",
        story: "[Business Context] Nhu cầu thuê xe ngắn hạn đang tăng nhưng quy trình truyền thống lại tốn thời gian. Giải pháp đề xuất là xây dựng Online Car Rental System. [Requirements] Khi Khách hàng muốn thuê xe, họ sử dụng hệ thống để Xem danh sách xe, Đặt thuê xe và Thanh toán cọc trực tuyến. Dữ liệu giao dịch được lưu tự động vào bảng Booking_Table. Khi có đơn mới, Nhân viên sẽ thực hiện Xác nhận đơn thuê và Kiểm tra xe khi hoàn trả. Quản trị viên (Admin) chịu trách nhiệm Quản lý tài khoản để hệ thống vận hành trơn tru.",
        instruction: "Đọc đoạn yêu cầu trên và phân loại các từ khóa vào đúng vùng trước khi bắt tay vào vẽ sơ đồ.",
        type: "SORT_BLOCKS",
        data: {
          zones: [
            { id: "actor", label: "Actor" },
            { id: "usecase", label: "Use Case" },
            { id: "noise", label: "Chi tiết kỹ thuật (Không vẽ)" }
          ],
          blocks: [
            { id: "customer", label: "Khách hàng", correctZoneId: "actor" },
            { id: "browse", label: "Xem danh sách xe", correctZoneId: "usecase" },
            { id: "book", label: "Đặt thuê xe", correctZoneId: "usecase" },
            { id: "pay", label: "Thanh toán cọc", correctZoneId: "usecase" },
            { id: "db", label: "Bảng Booking_Table", correctZoneId: "noise", feedback: "Table/Database là chi tiết lưu trữ kỹ thuật bên trong, ta sẽ không vẽ nó lên Use Case Diagram.", visualEffect: "backendRoom" },
            { id: "staff", label: "Nhân viên", correctZoneId: "actor" },
            { id: "confirm", label: "Xác nhận đơn thuê", correctZoneId: "usecase" },
            { id: "inspect", label: "Kiểm tra xe", correctZoneId: "usecase" },
            { id: "admin", label: "Quản trị viên (Admin)", correctZoneId: "actor" },
            { id: "manage", label: "Quản lý tài khoản", correctZoneId: "usecase" }
          ],
          successSimulation: "Bạn đã bóc tách xong yêu cầu! Bây giờ hãy mang các viên gạch này sang bước tiếp theo để ráp thành sơ đồ.",
          successVisualEffect: "successPath"
        }
      },
      {
        id: "project-01",
        title: "Run Diagram Scenario",
        story: "Xây boundary, đặt actors, đặt use cases, nối actor với use case, rồi chạy 3 scenario kiểm thử.",
        instruction: "Chọn actor, use case và nối các cặp cần thiết. Có thể cố tình nối sai rồi Run để thấy hệ thống dừng ở lỗi.",
        type: "RUN_DIAGRAM_SCENARIO",
        data: {
          systemLabel: "Online Car Rental System",
          actors: [
            { id: "customer", label: "Khách hàng", kind: "human" },
            { id: "staff", label: "Nhân viên", kind: "human" },
            { id: "admin", label: "Admin", kind: "human" },
            { id: "gateway", label: "Cổng thanh toán", kind: "system" },
          ],
          useCases: [
            { id: "browse", label: "Xem danh sách xe" },
            { id: "book", label: "Đặt thuê xe" },
            { id: "pay", label: "Thanh toán cọc" },
            { id: "confirm", label: "Xác nhận đơn thuê" },
            { id: "inspect", label: "Kiểm tra xe" },
            { id: "manage", label: "Quản lý tài khoản" },
          ],
          correctConnections: [
            c("customer", "browse"), 
            c("customer", "book"), 
            c("customer", "pay"), 
            c("gateway", "pay"),
            c("staff", "confirm"),
            c("staff", "inspect"),
            c("admin", "manage")
          ],
          scenarios: [
            { id: "booking", title: "Khách hàng đặt xe", path: ["Khách hàng", "Xem danh sách xe", "Đặt thuê xe", "Thanh toán cọc", "Cổng thanh toán"], requiredActors: ["customer", "gateway"], requiredUseCases: ["browse", "book", "pay"], requiredConnections: [c("customer", "browse"), c("customer", "book"), c("customer", "pay"), c("gateway", "pay")], feedback: "Khách hàng cần xem xe, đặt xe, thanh toán. Nhớ nối Cổng thanh toán vào Use Case thanh toán!" },
            { id: "staff_duty", title: "Nhân viên làm nhiệm vụ", path: ["Nhân viên", "Xác nhận đơn thuê", "Kiểm tra xe"], requiredActors: ["staff"], requiredUseCases: ["confirm", "inspect"], requiredConnections: [c("staff", "confirm"), c("staff", "inspect")], feedback: "Nhân viên phải được nối với Xác nhận đơn thuê và Kiểm tra xe." },
            { id: "admin_duty", title: "Admin quản trị", path: ["Admin", "Quản lý tài khoản"], requiredActors: ["admin"], requiredUseCases: ["manage"], requiredConnections: [c("admin", "manage")], feedback: "Admin phải được nối với use case Quản lý tài khoản." },
          ],
          successSimulation: "Cả 3 scenario chạy thành công. Sơ đồ đầu tiên đã mô tả chuẩn xác hệ thống Car Rental!",
        },
      },
    ],
  },
];
