import type { Lesson, VisualEffect } from "./types";

const fb = (feedback: string, simulation = feedback, visualEffect?: VisualEffect) => ({ feedback, simulation, visualEffect });
const c = (actorId: string, useCaseId: string) => ({ actorId, useCaseId });

export const interactiveLessons: Lesson[] = [
  {
    id: "intro-machine",
    title: "Lesson 0: Who does the system create value for?",
    description: "Before learning Use Cases, look at the system from the outside: a person or actor interacts with the system to achieve a useful result.",
    steps: [
      {
        id: "intro-01",
        title: "Actor -> System -> Goal",
        story: "Actor -> System -> Goal. Student -> FPTU Club Management System -> Find a suitable club. A new student wants to find a club that matches their interests. You are designing a club management system to support that student.",
        instruction: "Drag the blocks to the correct zones.",
        type: "SORT_BLOCKS",
        data: {
          zones: [
            { id: "student-goal", label: "Goal the student wants to achieve" },
            { id: "internal-detail", label: "How to do it / UI / Internal processing" },
          ],
          blocks: [
            {
              id: "find-club",
              label: "Find a suitable club",
              correctZoneId: "student-goal",
              successFeedback: "Correct. This is the useful result the student wants to achieve when using the system.",
            },
            {
              id: "view-list",
              label: "View club list",
              correctZoneId: "student-goal",
              successFeedback: "Correct. The student can use the system to view existing clubs before choosing a suitable one.",
            },
            {
              id: "enter-keyword",
              label: "Enter search keyword",
              correctZoneId: "internal-detail",
              feedback: "Incorrect. Entering a keyword is a UI action. If the system later switches to auto-suggestions or voice search, the student's goal is still to find a suitable club.",
            },
            {
              id: "view-detail",
              label: "View club details",
              correctZoneId: "student-goal",
              successFeedback: "Correct. This is a useful result because the student needs to know specific information about the club before deciding to show interest or join.",
            },
            {
              id: "search-button",
              label: "Click Search button",
              correctZoneId: "internal-detail",
              feedback: "Incorrect. Clicking a button is a UI action. If the UI changes, the Search button might be gone, but the goal of finding a club remains.",
            },
          ],
          successSimulation: "When identifying a Use Case, start with the goal the Actor wants to achieve. In this example, the Actor is the Student.",
          mixedSimulation: "The important point is not how the system processes things, but what value the student receives from the system.",
        },
      },
      {
        id: "intro-02",
        title: "Success Insight",
        type: "INSIGHT",
        data: {
          text: "When identifying a Use Case, start with the ______ that the Actor wants to achieve. In this example, the Actor is the ______. The important thing is that the Actor receives ______ from the system: view club list, find a suitable club, and get necessary information before deciding to join.",
          answers: ["goal", "Student", "value"],
          finalInsight: "When identifying a Use Case, start with the goal that the Actor wants to achieve. In this example, the Actor is the Student. The important thing is that the Actor receives value from the system: view club list, find a suitable club, and get necessary information before deciding to join.",
        },
      },
    ],
  },
  {
    id: "what-not-how",
    title: "Lesson 1: What is a Use Case?",
    description: "Cinema Booking System: view Use Cases as goals and value that Actors want to achieve, not UI, databases, APIs, or technical processing.",
    steps: [
      {
        id: "what-01",
        title: "Build booking goal",
        story: "You are designing a Cinema Booking System. A customer opens the system because they want to book a movie ticket for the weekend. Drag into the system frame the cards that represent the goals the user truly wants to achieve.",
        instruction: "Drag the appropriate cards into the Cinema Booking System frame, then click Run.",
        type: "DRAG_TO_BOUNDARY",
        data: {
          boundaryLabel: "Cinema Booking System",
          zones: [
            { id: "inside", label: "Inside System Boundary" },
            { id: "exclude", label: "Do not include in Use Case Diagram" },
          ],
          blocks: [
            { id: "chooseMovie", label: "Choose movie", correctZoneId: "inside" },
            { id: "chooseShowtime", label: "Choose showtime", correctZoneId: "inside" },
            { id: "chooseSeat", label: "Choose seat", correctZoneId: "inside" },
            { id: "payTicket", label: "Pay for ticket", correctZoneId: "inside" },
            { id: "receiveTicket", label: "Receive e-ticket", correctZoneId: "inside" },
            {
              id: "queryMovies",
              label: "Query movie list",
              correctZoneId: "exclude",
              feedback: "Don't worry, this is related, but querying the database means fetching data from the DB. This is internal processing, not a goal stated by the customer.",
              simulation: "A stickman customer walks to 'Query movie list' and stops with a question mark: 'I don't know what query database is. I just want to choose a movie.'",
              visualEffect: "backendRoom",
            },
            {
              id: "callVnpay",
              label: "Call VNPay API",
              correctZoneId: "exclude",
              feedback: "This confusion is very common when learning Use Cases. An API is how the system communicates with another system. A Use Case should not be tied to a specific payment gateway.",
              simulation: "The timeline switches from VNPay to Momo. The 'Call VNPay API' block cracks: 'The payment gateway changed. The Use Case tied to VNPay is outdated.'",
              visualEffect: "outdatedTechnology",
            },
            {
              id: "renderTicket",
              label: "Render ticket UI",
              correctZoneId: "exclude",
              feedback: "Rendering the UI means drawing or displaying the screen for the user. This is a UI detail. The customer's goal is to receive or view the e-ticket.",
              simulation: "A beautiful loading UI appears, but the customer is still waiting: 'I see the screen, but where is my ticket?'",
              visualEffect: "uiChanged",
            },
            {
              id: "lockSeat",
              label: "Lock seat temporarily",
              correctZoneId: "exclude",
              feedback: "Close, but this is a supporting mechanism, not the main goal yet. From the Actor's perspective, the closer goal is Choose seat.",
              simulation: "A seat is locked for 5 minutes. The customer looks at their watch and asks: 'So, have I chosen my seat yet?'",
              visualEffect: "lockedSeat",
            },
            {
              id: "saveTicket",
              label: "Save ticket to database",
              correctZoneId: "exclude",
              feedback: "A database is where data is stored. Saving the ticket is crucial for the system, but the Use Case should state the value the customer receives: Receive e-ticket.",
              simulation: "The database lights up green, but the customer is still waiting at the counter: 'The data is saved, where is my ticket?'",
              visualEffect: "backendRoom",
            },
          ],
          scenario: ["Customer", "Choose movie", "Choose showtime", "Choose seat", "Pay for ticket", "Receive e-ticket"],
          successSimulation: "The stickman customer completes the journey: Choose movie -> Choose showtime -> Choose seat -> Pay for ticket -> Receive e-ticket. At the end, the e-ticket pops up with a smiley face.",
          successVisualEffect: "successPath",
        },
      },
      {
        id: "what-02",
        title: "Main goal or just a stepping stone?",
        story: "The customer says: 'I want to book a movie ticket for tonight.' Choose the most appropriate Use Case name for this entire goal.",
        instruction: "Select a Use Case name then click Run.",
        type: "SELECT_BLOCK_AND_RUN",
        data: {
          correctId: "bookTicket",
          blocks: [
            { id: "viewSchedule", label: "View schedule" },
            { id: "checkSeats", label: "Check available seats" },
            { id: "bookTicket", label: "Book movie ticket" },
            { id: "payTicket", label: "Pay for ticket" },
            { id: "receiveTicket", label: "Receive e-ticket" },
          ],
          feedbackByBlock: {
            viewSchedule: fb("Close, but this is just a supporting step, it does not cover the ticket booking goal.", "The customer views the schedule and then stops: 'Great, but I still don't have a ticket.'", "stopAtNode"),
            checkSeats: fb("Not absolutely wrong. But in the booking context, it is a supporting step for Choose seat or Book ticket.", "The seat map shows some red and green seats. The customer looks and says: 'I know there are seats, but I still haven't booked.'", "bounceBack"),
            bookTicket: fb("Correct. This is the Actor's overarching goal: the customer wants the system to help them book a movie ticket.", "The customer completes the journey and receives the e-ticket. Great, the main goal was named correctly.", "successPath"),
            payTicket: fb("Paying for the ticket is an important Use Case, but not the overarching goal of this entire journey.", "A POS machine appears instantly, but the customer hesitates: 'Which movie, showtime, or seat am I paying for?'", "stopAtNode"),
            receiveTicket: fb("This is the final result or post-condition. It is related, but not necessarily the main Use Case for the whole booking goal.", "The e-ticket appears but the system flashes red: 'Cannot receive a ticket without booking and paying.'", "bounceBack"),
          },
        },
      },
      {
        id: "what-03",
        title: "Which name survives when technology changes?",
        story: "The cinema changes its payment technology through versions. Version 1: VNPay. Version 2: Momo. Version 3: Internal cinema wallet.",
        instruction: "Choose the Use Case name that remains correct across all 3 versions.",
        type: "SELECT_BLOCK_AND_RUN",
        data: {
          correctId: "payTicket",
          blocks: [
            { id: "callVnpay", label: "Call VNPay API" },
            { id: "callMomo", label: "Call Momo API" },
            { id: "payTicket", label: "Pay for ticket" },
            { id: "verifyCallback", label: "Verify VNPay callback" },
            { id: "saveTransaction", label: "Save transactionId" },
          ],
          feedbackByBlock: {
            callVnpay: fb("You are tying the Use Case to a specific technology. An API is how two systems communicate, not the Actor's goal.", "The timeline runs fine on Version 1 VNPay, but on Version 2 Momo, the 'Call VNPay API' block breaks: 'VNPay was replaced by Momo.'", "outdatedTechnology"),
            callMomo: fb("Similar to the VNPay error: this name lives by the current technology, not by the user's goal.", "The timeline reaches Version 3 internal wallet. The 'Call Momo API' block cracks: 'Momo was replaced by the internal wallet.'", "outdatedTechnology"),
            payTicket: fb("Correct. Technology changes, but the user's goal remains the same.", "The timeline VNPay -> Momo -> Internal wallet runs through all 3 versions. The 'Pay for ticket' block remains green.", "successPath"),
            verifyCallback: fb("You are looking from a developer's perspective. A payment callback is a signal sent back to the system; this is a technical mechanism, not an Actor's goal.", "The screen switches to the backend log, the customer disappears from the scene. The log scrolls continuously but no one sees the booking goal.", "backendRoom"),
            saveTransaction: fb("This is technical storage. The transactionId is an ID for the system to track payments, not what the customer wants to achieve.", "The database appears, a transactionId row lights up green. The customer waits outside asking: 'Where is my ticket?'", "backendRoom"),
          },
        },
      },
      {
        id: "what-04",
        title: "When Use Case Diagram becomes a flowchart",
        story: "Someone drew an overly detailed diagram for the booking process. Select the blocks that should be kept as Use Cases, and remove the steps that turn the diagram into a flowchart.",
        type: "SORT_BLOCKS",
        data: {
          zones: [
            { id: "keep", label: "Keep as Use Case" },
            { id: "flowchart", label: "Too detailed / flowchart step" },
          ],
          blocks: [
            { id: "chooseMovie", label: "Choose movie", correctZoneId: "keep" },
            { id: "chooseShowtime", label: "Choose showtime", correctZoneId: "keep" },
            { id: "chooseSeat", label: "Choose seat", correctZoneId: "keep" },
            { id: "ticketQuantity", label: "Enter ticket quantity", correctZoneId: "flowchart", feedback: "Close, because it's part of the journey, but this name is too narrow. It makes the diagram look like a step-by-step UI flow.", simulation: "The diagram adds a small node. The stickman passes it but gets stuck entering quantity, the scope meter increases.", visualEffect: "flowchartWarning" },
            { id: "continueButton", label: "Click Continue button", correctZoneId: "flowchart", feedback: "This is a UI action. If the button changes to a swipe, auto-next, or voice command, the user's goal remains unchanged.", simulation: "The Continue button zooms in. The stickman clicks it but the diagram doesn't clarify the value achieved.", visualEffect: "flowchartWarning" },
            { id: "checkSeat", label: "Check available seats", correctZoneId: "flowchart", feedback: "Not completely wrong, but in this context, it's a supporting step for Choose seat, not the main goal.", simulation: "A red/green seat map appears, then the journey gets stuck between checking and choosing. Warning: 'You are describing the path, not the destination.'", visualEffect: "bounceBack" },
            { id: "lockSeat", label: "Lock seat for 5 mins", correctZoneId: "flowchart", feedback: "This is a supporting mechanism inside the system. Use Case Diagrams shouldn't describe small internal processes like temporarily holding a seat.", simulation: "A 5-minute clock appears, the node squeezes in the middle. The complexity meter jumps up.", visualEffect: "flowchartWarning" },
            { id: "payTicket", label: "Pay for ticket", correctZoneId: "keep" },
            { id: "receiveTicket", label: "Receive e-ticket", correctZoneId: "keep" },
          ],
          successSimulation: "The diagram simplifies into 5 main goals: Choose movie, Choose showtime, Choose seat, Pay for ticket, Receive e-ticket. The reader understands what the system helps the customer do without drowning in clicks.",
          successVisualEffect: "successPath",
          mixedSimulation: "The diagram bloats, nodes crowd together, the stickman has to take too many steps. Warning: Use Case Diagram should describe goals, not every click or small process.",
          mixedVisualEffect: "flowchartWarning",
        },
      },
      {
        id: "what-05",
        title: "Change the Actor, change the goal",
        story: "In the same Cinema Booking System, each Actor interacts with the system for a different goal. Keep the associations that represent the correct goals, and remove the links that only describe technical actions.",
        instruction: "Select an Actor then select an appropriate Use Case to create a connection. Only connect the correct goals.",
        type: "CONNECT_ACTOR_TO_USECASE",
        data: {
          actors: [
            { id: "customer", label: "Customer", kind: "human" },
            { id: "staff", label: "Cinema Staff", kind: "human" },
            { id: "paymentGateway", label: "Payment Gateway", kind: "system" },
          ],
          useCases: [
            { id: "bookTicket", label: "Book movie ticket" },
            { id: "confirmTicket", label: "Confirm ticket at cinema" },
            { id: "confirmPayment", label: "Confirm payment result" },
            { id: "scanQr", label: "Scan ticket QR code" },
            { id: "paymentCallback", label: "Call payment callback" },
          ],
          correctConnections: [c("customer", "bookTicket"), c("staff", "confirmTicket"), c("paymentGateway", "confirmPayment")],
          feedbackByConnection: {
            "customer->confirmPayment": fb("You are looking through the wrong Actor lens. The customer doesn't need to verify payment logs; they want to know if they bought the ticket.", "The customer looks at the payment log screen and is confused: 'I just want to know if I got my ticket.'", "backendRoom"),
            "customer->scanQr": fb("The customer can present the QR code, but their goal is not to scan it. Confirming the ticket at the gate usually belongs to the Cinema Staff. The stable Use Case is Confirm ticket at cinema.", "The customer presents the QR code, but the one scanning it is the staff. If they switch to NFC, the ticket confirmation goal remains.", "outdatedTechnology"),
            "staff->scanQr": fb("Scanning QR is the current method. If they later use NFC or a ticket number, the Use Case should still be Confirm ticket at cinema.", "The QR scanner is replaced by an NFC gate. The 'Scan ticket QR code' block is marked outdated, but the confirmation goal survives.", "outdatedTechnology"),
            "paymentGateway->paymentCallback": fb("Payment callback is how the gateway sends results to the system. This is a technical communication detail. At the Use Case level, we should describe the goal as Confirm payment result.", "The screen shows an API callback log. The payment gateway wants to report the result, not drown the reader in protocols.", "backendRoom"),
          },
          successSimulation: "Correct. Each Actor is now connected to their appropriate goal: Customer books ticket, Staff confirms ticket, Payment Gateway confirms payment result.",
          successVisualEffect: "successPath",
        },
      },
      {
        id: "what-06",
        title: "Use Case Emergency Room",
        story: "A Use Case diagram is infected with code, UI, and database details. Save it.",
        type: "SORT_BLOCKS",
        data: {
          zones: [
            { id: "keep", label: "Keep" },
            { id: "rename", label: "Rename" },
            { id: "remove", label: "Remove" },
          ],
          blocks: [
            { id: "bookTicket", label: "Book movie ticket", correctZoneId: "keep", successFeedback: "Good Use Case: speaks the customer's goal." },
            { id: "queryMovie", label: "Query Movie table", correctZoneId: "remove", feedback: "Query Movie table means fetching data from the Movie DB table. This is a storage detail, put it in the Internal bin.", simulation: "The database block is moved to the 'Internal' bin.", visualEffect: "backendRoom" },
            { id: "callVnpay", label: "Call VNPay API", correctZoneId: "remove", feedback: "API is how systems communicate. This name depends on technology and should be removed.", simulation: "The API block is put in the Internal bin. The timeline switches to another wallet.", visualEffect: "outdatedTechnology" },
            { id: "scanQr", label: "Scan ticket QR code", correctZoneId: "rename", feedback: "Close, but too narrow to the current method. Rename to Confirm ticket at cinema to survive NFC changes.", simulation: "The block passes through the Rename Machine and becomes 'Confirm ticket at cinema'.", visualEffect: "outdatedTechnology" },
            { id: "confirmTicket", label: "Confirm ticket at cinema", correctZoneId: "keep", successFeedback: "Good Use Case: speaks the cinema staff's business goal." },
            { id: "renderQr", label: "Render ticket QR code", correctZoneId: "remove", feedback: "Rendering a QR code is a UI/technical detail, not an Actor's goal.", simulation: "The QR drawing screen lights up but the diagram is cluttered. The Use Case doctor puts it in the Internal bin.", visualEffect: "backendRoom" },
            { id: "viewTicket", label: "View booked ticket", correctZoneId: "keep", successFeedback: "Good Use Case: the customer receives clear value." },
            { id: "insertTicket", label: "Insert Ticket Record", correctZoneId: "remove", feedback: "Inserting a record means saving a row in the DB. This is an internal storage detail.", simulation: "The database lights up, but the Actor disappears. The block is put in the Internal bin.", visualEffect: "backendRoom" },
            { id: "checkSeat", label: "Check available seats", correctZoneId: "rename", feedback: "Not completely wrong. In this lesson, rename it to View seat availability or Choose seat to better express the user's goal.", simulation: "The block passes through the Rename Machine: 'Check available seats' becomes 'View seat availability' or 'Choose seat'.", visualEffect: "renameMachine" },
            { id: "lockSeat", label: "Lock seat for 5 mins", correctZoneId: "remove", feedback: "This is an internal supporting mechanism, not an independent goal.", simulation: "The 5-minute clock is pulled from the diagram. Good Use Cases turn green, technical details go to Internal.", visualEffect: "flowchartWarning" },
          ],
          successSimulation: "The diagram is clean again: Book movie ticket, Confirm ticket at cinema, View booked ticket. Now the diagram speaks the Actor's language, not code.",
          successVisualEffect: "successPath",
          mixedSimulation: "The Use Case emergency room is operating: code/DB into the Internal bin, narrow names through the Rename Machine, good Use Cases turn green.",
          mixedVisualEffect: "renameMachine",
        },
      },
      {
        id: "what-07",
        title: "Run Diagram: Does the customer get the ticket?",
        story: "The customer wants to book a movie ticket online. If the Use Case Diagram is correct, the journey will reach the final goal: Receive ticket. If you select technical actions or miss an important Use Case, the journey will get stuck.",
        instruction: "Select the necessary Use Cases for the booking journey. Then connect the Customer Actor to the main goal and click Run Simulation.",
        type: "RUN_DIAGRAM_SCENARIO",
        data: {
          mode: "useCaseRunSimulation",
          systemLabel: "Cinema Booking System",
          goalText: "The customer wants to book a ticket and receive an e-ticket. The diagram passes when the journey covers the main goals without mixing in technical details.",
          idleGoal: "Test goal: The customer wants to book a movie ticket and receive the ticket.",
          passCondition: "Pass condition: select the correct Use Cases, no technical blocks, ending with the Receive ticket goal.",
          actors: [{ id: "customer", label: "Customer", kind: "human" }],
          useCases: [
            { id: "viewSchedule", label: "View schedule", icon: "Calendar" },
            { id: "bookTicket", label: "Book movie ticket", icon: "Ticket" },
            { id: "chooseSeat", label: "Choose seat", icon: "Seat" },
            { id: "payTicket", label: "Pay for ticket", icon: "Pay" },
            { id: "receiveTicket", label: "Receive ticket", icon: "QR" },
          ],
          journeySteps: [
            { id: "viewSchedule", label: "View schedule", icon: "Calendar" },
            { id: "bookTicket", label: "Book movie ticket", icon: "Ticket" },
            { id: "chooseSeat", label: "Choose seat", icon: "Seat" },
            { id: "payTicket", label: "Pay for ticket", icon: "Pay" },
            { id: "receiveTicket", label: "Receive ticket", icon: "QR" },
          ],
          distractors: [
            { id: "queryMovie", label: "Query Movie table", feedback: "Querying the Movie table is how the system fetches data. This is an internal detail, not a Use Case.", suggestion: "In a Use Case Diagram, use View schedule or Book movie ticket instead.", visualEffect: "backendRoom" },
            { id: "renderSeat", label: "Render seat UI", feedback: "Rendering the seat UI is a technical step. This block might be correct in UI design, but not in a Use Case Diagram.", suggestion: "In a Use Case Diagram, use Choose seat.", visualEffect: "uiChanged" },
            { id: "callVnpay", label: "Call VNPay API", feedback: "Calling an API is internal payment processing, not a goal the customer directly accomplishes.", suggestion: "In a Use Case Diagram, use Pay for ticket.", visualEffect: "outdatedTechnology" },
            { id: "lockSeat", label: "Lock seat for 5 mins", feedback: "Locking a seat is a temporary internal mechanism. This block might be correct in an activity diagram, but not in a Use Case Diagram.", suggestion: "In a Use Case Diagram, use Choose seat.", visualEffect: "flowchartWarning" },
            { id: "insertTicket", label: "Insert Ticket Record", feedback: "Inserting a record is a database operation, not suitable for a Use Case Diagram.", suggestion: "In a Use Case Diagram, use Receive ticket.", visualEffect: "backendRoom" },
          ],
          correctConnections: [
            c("customer", "viewSchedule"),
            c("customer", "bookTicket"),
            c("customer", "chooseSeat"),
            c("customer", "payTicket"),
            c("customer", "receiveTicket"),
          ],
          missingFeedback: {
            payTicket: {
              feedbackBody: "❌ The customer chose a seat but cannot finish booking.",
              suggestion: "The journey is missing the Pay for ticket Use Case. Without this core value step, the actor cannot achieve the final goal.",
            },
            receiveTicket: {
              feedbackBody: "❌ Payment is done but the customer didn't receive the ticket.",
              suggestion: "The Use Case Diagram is missing the final goal: Receive ticket. A good Use Case must show the valuable result for the actor.",
            },
          },
          scenarios: [
            {
              id: "bookingJourney",
              title: "Customer receives ticket",
              path: ["Customer", "View schedule", "Book movie ticket", "Choose seat", "Pay for ticket", "Receive ticket"],
              requiredActors: ["customer"],
              requiredUseCases: ["viewSchedule", "bookTicket", "chooseSeat", "payTicket", "receiveTicket"],
              requiredConnections: [c("customer", "viewSchedule"), c("customer", "bookTicket"), c("customer", "chooseSeat"), c("customer", "payTicket"), c("customer", "receiveTicket")],
              feedback: fb("The journey isn't enough for the customer to receive the ticket. Re-check the core goals: schedule, book, choose seat, pay, and receive.", "The run customer journey gets cut midway.", "stopAtNode"),
            },
          ],
          successSimulation: "✅ The customer received their ticket! Your diagram focuses on user goals: view schedule, book, choose seat, pay, and receive.",
          successVisualEffect: "ticketSuccess",
        },
      },
      {
        id: "what-08",
        title: "Insight Fill",
        type: "INSIGHT",
        data: {
          text: "When identifying a Use Case, always start from the ______ that the Actor wants to achieve. A Use Case should speak in the ______'s language, not code. A good Use Case describes the ______ the user receives, not every single ______, UI, database, or API.",
          answers: ["goal", "Actor", "value", "processing step"],
          finalInsight: "When identifying a Use Case, always start from the goal that the Actor wants to achieve. A Use Case should speak in the Actor's language, not code. A good Use Case describes the value the user receives, not every single processing step, UI, database, or API.",
          mantra: "A Use Case answers the question: What does the system help the Actor achieve? It does NOT answer: How does the system process this internally?",
        },
      },
    ],
  },
  {
    id: "system-boundary",
    title: "Lesson 2: System Boundary",
    description: "Use Cases are inside the boundary; Actors and external systems are outside.",
    steps: [
      {
        id: "boundary-01",
        title: "Online Clothing Store Boundary",
        story: "You are building an online clothing store app. What goes inside the box is what your team is responsible for as core features.",
        type: "DRAG_TO_BOUNDARY",
        data: {
          boundaryLabel: "Online Clothing Store App",
          zones: [
            { id: "inside", label: "Inside System Boundary" },
            { id: "outside", label: "Outside System Boundary" },
            { id: "exclude", label: "Do not include in Use Case Diagram" },
          ],
          blocks: [
            { id: "customer", label: "Customer", correctZoneId: "outside", feedback: "The customer is an Actor." },
            { id: "view", label: "View products", correctZoneId: "inside" },
            { id: "cart", label: "Add to cart", correctZoneId: "inside" },
            { id: "pay", label: "Pay for order", correctZoneId: "inside" },
            { id: "zalo", label: "ZaloPay", correctZoneId: "outside", feedback: "ZaloPay is an external system." },
            { id: "shipper", label: "Shipping Unit", correctZoneId: "outside" },
            { id: "db", label: "Product Database", correctZoneId: "exclude", feedback: "Database is a technical design detail, no need to draw it in a Use Case Diagram." },
          ],
          successSimulation: "Clear scope: the system contains features, outside are actors and supporting systems.",
        },
      },
      {
        id: "boundary-02",
        title: "Boundary Resize Simulation",
        instruction: "Fix it so Actors are outside, Use Cases are inside, external systems are outside, and databases are excluded from the diagram.",
        type: "DRAG_TO_BOUNDARY",
        data: {
          boundaryLabel: "Scope Meter",
          zones: [
            { id: "inside", label: "Inside Boundary" },
            { id: "outside", label: "Outside Boundary" },
            { id: "exclude", label: "Exclude from diagram" },
          ],
          blocks: [
            { id: "actor", label: "Customer", correctZoneId: "outside", penalty: "Scope +20%" },
            { id: "uc", label: "View products", correctZoneId: "inside" },
            { id: "payment", label: "Payment Gateway", correctZoneId: "outside", penalty: "Scope +50%" },
            { id: "database", label: "Product Database", correctZoneId: "exclude", penalty: "Complexity +30%" },
          ],
          initialPlacements: { actor: "inside", uc: "outside", payment: "inside", database: "inside" },
          successSimulation: "Scope meter is stable: the team didn't accidentally take on building the actor, payment gateway, or database design in the diagram.",
        },
      },
      {
        id: "boundary-03",
        title: "FPTU Club Boundary",
        type: "DRAG_TO_BOUNDARY",
        data: {
          boundaryLabel: "FPTU Club Management System",
          zones: [
            { id: "inside", label: "Inside Boundary" },
            { id: "outside", label: "Outside Boundary" },
            { id: "exclude", label: "Exclude from diagram" },
          ],
          blocks: [
            { id: "student", label: "Student", correctZoneId: "outside" },
            { id: "admin", label: "Admin", correctZoneId: "outside" },
            { id: "list", label: "View club list", correctZoneId: "inside" },
            { id: "search", label: "Search club info", correctZoneId: "inside" },
            { id: "approve", label: "Approve club info", correctZoneId: "inside" },
            { id: "google", label: "Google Login", correctZoneId: "outside" },
            { id: "email", label: "Email Service", correctZoneId: "outside" },
            { id: "table", label: "Club Table", correctZoneId: "exclude" },
          ],
          successSimulation: "FPTU Club System now has clear responsibility boundaries.",
        },
      },
      {
        id: "boundary-04",
        title: "Fix Broken Diagram",
        type: "DRAG_TO_BOUNDARY",
        data: {
          boundaryLabel: "Broken FPTU Club Diagram",
          zones: [
            { id: "inside", label: "Inside Boundary" },
            { id: "outside", label: "Outside Boundary" },
            { id: "exclude", label: "Exclude from diagram" },
          ],
          blocks: [
            { id: "student", label: "Student", correctZoneId: "outside" },
            { id: "admin", label: "Admin", correctZoneId: "outside" },
            { id: "list", label: "View club list", correctZoneId: "inside" },
            { id: "google", label: "Google Login", correctZoneId: "outside" },
            { id: "table", label: "Club Table", correctZoneId: "exclude" },
            { id: "search", label: "Search club info", correctZoneId: "inside" },
          ],
          initialPlacements: { student: "inside", admin: "inside", list: "inside", google: "inside", table: "inside", search: "outside" },
          successSimulation: "The diagram is fixed: actor and Google Login moved outside, table disappeared, Use Case moved inside.",
        },
      },
      {
        id: "boundary-05",
        title: "Boundary Stress Test",
        type: "RUN_DIAGRAM_SCENARIO",
        data: {
          systemLabel: "FPTU Club Management System",
          actors: [
            { id: "student", label: "Student", kind: "human" },
            { id: "admin", label: "Admin", kind: "human" },
            { id: "email", label: "Email Service", kind: "system" },
          ],
          useCases: [
            { id: "search", label: "Search club info" },
            { id: "approve", label: "Approve club info" },
            { id: "send", label: "Send confirmation email" },
          ],
          correctConnections: [c("student", "search"), c("admin", "approve"), c("email", "send")],
          scenarios: [
            { id: "s1", title: "Student wants to find a club", path: ["Student", "Search club info"], requiredActors: ["student"], requiredUseCases: ["search"], requiredConnections: [c("student", "search")], feedback: "Need Student outside boundary and Search club info inside boundary." },
            { id: "s2", title: "Admin wants to approve club info", path: ["Admin", "Approve club info"], requiredActors: ["admin"], requiredUseCases: ["approve"], requiredConnections: [c("admin", "approve")], feedback: "Need Admin connected correctly to approve use case." },
            { id: "s3", title: "System sends confirmation email", path: ["Email Service", "Send confirmation email"], requiredActors: ["email"], requiredUseCases: ["send"], requiredConnections: [c("email", "send")], feedback: "Email Service is an external actor outside the boundary." },
          ],
          successSimulation: "All three scenarios run correctly across the boundary.",
        },
      },
      {
        id: "boundary-06",
        title: "Insight",
        type: "INSIGHT",
        data: {
          text: "Actors are ______. Use Cases are ______. External systems are also ______. Databases do not need to be drawn in a Use Case Diagram.",
          answers: ["outside", "inside", "outside"],
          finalInsight: "Actors are outside. Use Cases are inside. External systems are also outside. Databases do not need to be drawn in a Use Case Diagram.",
        },
      },
    ],
  },
  {
    id: "actor",
    title: "Lesson 3: Actors are not just humans",
    description: "An Actor is a role, an external system, or a time trigger.",
    steps: [
      {
        id: "actor-01",
        title: "Auto Cleanup Actor",
        story: "Every day at 00:00, the system automatically deletes abandoned draft orders.",
        type: "CONNECT_ACTOR_TO_USECASE",
        data: {
          actors: [
            { id: "customer", label: "Customer", kind: "human" },
            { id: "admin", label: "Admin", kind: "human" },
            { id: "time", label: "Time: 00:00 daily", kind: "time" },
          ],
          useCases: [{ id: "cleanup", label: "Auto-clean draft orders" }],
          correctConnections: [c("time", "cleanup")],
          feedbackByConnection: {
            "customer->cleanup": "Incorrect because the customer doesn't have to stay up at night to press a button.",
            "admin->cleanup": "Incorrect because an automated feature would turn into a manual one.",
            "time->cleanup": "Correct because time triggers the automated feature.",
          },
          successSimulation: "At 00:00, the system auto-triggers cleanup without human intervention.",
        },
      },
      {
        id: "actor-02",
        title: "Actor Type Sorting",
        type: "SORT_BLOCKS",
        data: {
          zones: [
            { id: "human", label: "Human Actor" },
            { id: "system", label: "External System Actor" },
            { id: "time", label: "Time Actor" },
          ],
          blocks: [
            { id: "student", label: "Student", correctZoneId: "human" },
            { id: "admin", label: "Admin", correctZoneId: "human" },
            { id: "club", label: "Club Board", correctZoneId: "human" },
            { id: "payment", label: "Payment Gateway", correctZoneId: "system" },
            { id: "google", label: "Google Login", correctZoneId: "system" },
            { id: "email", label: "Email Service", correctZoneId: "system" },
            { id: "midnight", label: "00:00 daily", correctZoneId: "time" },
            { id: "month", label: "End of month", correctZoneId: "time" },
          ],
          successSimulation: "Actors are not only humans: external systems and time can also trigger Use Cases.",
        },
      },
      {
        id: "actor-03",
        title: "Actor or Use Case",
        type: "SORT_BLOCKS",
        data: {
          zones: [
            { id: "actor", label: "Actor" },
            { id: "usecase", label: "Use Case" },
          ],
          blocks: [
            { id: "student", label: "Student", correctZoneId: "actor" },
            { id: "list", label: "View club list", correctZoneId: "usecase" },
            { id: "search", label: "Search club info", correctZoneId: "usecase" },
            { id: "admin", label: "Admin", correctZoneId: "actor" },
            { id: "approve", label: "Approve club info", correctZoneId: "usecase" },
            { id: "mail", label: "Email gateway", correctZoneId: "actor" },
            { id: "send", label: "Send reminder email", correctZoneId: "usecase" },
            { id: "time", label: "07:00 daily", correctZoneId: "actor" },
          ],
          successSimulation: "Role nouns are outside; verb-based goals are inside the boundary.",
        },
      },
      {
        id: "actor-04",
        title: "Role, Not Person",
        story: "Nam is an FPTU student and also a member of the Guitar Club Board.",
        type: "SORT_BLOCKS",
        data: {
          zones: [
            { id: "draw", label: "Should draw as Actor" },
            { id: "skip", label: "Should not draw as Actor" },
          ],
          blocks: [
            { id: "nam", label: "Nam", correctZoneId: "skip" },
            { id: "student", label: "Student", correctZoneId: "draw" },
            { id: "club", label: "Club Board", correctZoneId: "draw" },
            { id: "shirt", label: "Person wearing a blue shirt", correctZoneId: "skip" },
          ],
          successSimulation: "Use Case Diagrams map roles, not specific individuals.",
        },
      },
      {
        id: "actor-05",
        title: "Connect Actor to Goal",
        type: "CONNECT_ACTOR_TO_USECASE",
        data: {
          actors: [
            { id: "student", label: "Student" },
            { id: "member", label: "Club Member" },
            { id: "lead", label: "Club Board" },
            { id: "admin", label: "Admin" },
            { id: "time", label: "07:00 daily" },
            { id: "email", label: "Email Service" },
          ],
          useCases: [
            { id: "list", label: "View club list" },
            { id: "internal", label: "View internal activities" },
            { id: "event", label: "Create event" },
            { id: "approve", label: "Approve club info" },
            { id: "send", label: "Send meeting reminder" },
          ],
          correctConnections: [c("student", "list"), c("member", "internal"), c("lead", "event"), c("admin", "approve"), c("time", "send"), c("email", "send")],
          feedbackByConnection: {
            "student->approve": "Wrong permissions: Students don't approve club info.",
            "email->event": "Incorrect: Email Service only handles sending notifications.",
          },
          successSimulation: "Each actor is connected to a goal that their role actually triggers or supports.",
        },
      },
      {
        id: "actor-06",
        title: "Insight",
        type: "INSIGHT",
        data: {
          text: "An Actor is an entity ______ the system, which can ______ with or ______ the system.",
          answers: ["outside", "interact", "trigger"],
          finalInsight: "An Actor is an entity outside the system, which can interact with or trigger the system.",
        },
      },
    ],
  },
  {
    id: "naming",
    title: "Lesson 4: Use Case Naming Rules",
    description: "A good name is usually a business verb + business object.",
    steps: [
      {
        id: "name-01",
        title: "Build Use Case Name",
        story: "The user wants to change their shipping address in their account.",
        type: "BUILD_USECASE_NAME",
        data: {
          verbs: [
            { id: "update", label: "Update" },
            { id: "manage", label: "Manage" },
            { id: "click", label: "Click" },
            { id: "api", label: "Call API" },
          ],
          nouns: [
            { id: "address", label: "shipping address" },
            { id: "form", label: "info form" },
            { id: "db", label: "user database" },
            { id: "profile", label: "personal profile" },
          ],
          acceptedPairs: [c("update", "address")],
          feedbackByPair: {
            "click->form": "Incorrect because it depends on UI.",
            "api->db": "Incorrect because it is technical.",
            "manage->profile": "Too broad for this scenario.",
            "update->address": "Clear business goal.",
          },
          successSimulation: "The oval name clearly states the action and business object: Update shipping address.",
        },
      },
      {
        id: "name-02",
        title: "Rename Broken Use Cases",
        type: "SORT_BLOCKS",
        data: {
          zones: [
            { id: "actor", label: "Move out as Actor" },
            { id: "rename", label: "Rename to good Use Case" },
            { id: "keep", label: "Keep as is" },
          ],
          blocks: [
            { id: "student", label: "Student", correctZoneId: "actor" },
            { id: "screen", label: "Club List Screen", correctZoneId: "rename", feedback: "Rename to View club list." },
            { id: "click", label: "Click Search Button", correctZoneId: "rename", feedback: "Rename to Search club info." },
            { id: "controller", label: "SearchClubController", correctZoneId: "rename", feedback: "Rename to Search club info." },
            { id: "insert", label: "Insert Club Table", correctZoneId: "rename", feedback: "Rename to Create or Update club info." },
            { id: "list", label: "View club list", correctZoneId: "keep" },
            { id: "search", label: "Search club info", correctZoneId: "keep" },
          ],
          successSimulation: "Broken names are categorized: actors moved out, UI/code/database renamed to business goals.",
        },
      },
      {
        id: "name-03",
        title: "Naming Error Detector",
        type: "SORT_BLOCKS",
        data: {
          zones: [
            { id: "actor", label: "Actor Name" },
            { id: "ui", label: "UI Detail" },
            { id: "code", label: "Code Detail" },
            { id: "db", label: "Database Detail" },
            { id: "good", label: "Good Use Case Name" },
          ],
          blocks: [
            { id: "admin", label: "Admin", correctZoneId: "actor" },
            { id: "button", label: "Login Button", correctZoneId: "ui" },
            { id: "auth", label: "AuthController", correctZoneId: "code" },
            { id: "insert", label: "Insert User Table", correctZoneId: "db" },
            { id: "login", label: "Login", correctZoneId: "good" },
            { id: "create", label: "Create account", correctZoneId: "good" },
            { id: "render", label: "Render Profile Page", correctZoneId: "ui" },
            { id: "update", label: "Update personal info", correctZoneId: "good" },
          ],
          successSimulation: "Name filter active: only business goal phrases are kept as Use Cases.",
        },
      },
      {
        id: "name-04",
        title: "Verb Strength Challenge",
        story: "Admin checks club information before making it public.",
        type: "SELECT_BLOCK_AND_RUN",
        data: {
          correctId: "approve",
          blocks: [
            { id: "manage", label: "Manage club" },
            { id: "process", label: "Process club info" },
            { id: "approve", label: "Approve club info" },
          ],
          feedbackByBlock: {
            manage: fb("Too broad."),
            process: fb("Vague."),
            approve: fb("Clear action and goal."),
          },
        },
      },
      {
        id: "name-05",
        title: "Build Names for FPTU Club System",
        type: "BUILD_USECASE_NAME",
        data: {
          verbs: [
            { id: "view", label: "View" },
            { id: "search", label: "Search" },
            { id: "create", label: "Create" },
            { id: "approve", label: "Approve" },
            { id: "send", label: "Send" },
            { id: "update", label: "Update" },
          ],
          nouns: [
            { id: "list", label: "club list" },
            { id: "info", label: "club info" },
            { id: "event", label: "event" },
            { id: "notice", label: "notification" },
            { id: "join", label: "join request" },
            { id: "internal", label: "internal activities" },
          ],
          acceptedPairs: [c("view", "list"), c("search", "info"), c("create", "event"), c("approve", "info"), c("send", "notice"), c("update", "info"), c("view", "internal")],
          requiredCount: 5,
          successSimulation: "You created a solid set of Use Case names for the FPTU Club System.",
        },
      },
      {
        id: "name-06",
        title: "Insight",
        type: "INSIGHT",
        data: {
          text: "A good Use Case name should be a ______ + ______, avoiding UI, code, databases, and APIs.",
          answers: ["business verb", "business object"],
          finalInsight: "A good Use Case name should be a business verb + business object, avoiding UI, code, databases, and APIs.",
        },
      },
    ],
  },
  {
    id: "mini-project",
    title: "Mini Project: Build Your First Use Case Diagram",
    description: "Build your first Use Case diagram for the FPTU Club Management System.",
    steps: [
      {
        id: "project-01",
        title: "Run Diagram Scenario",
        story: "Build the boundary, place actors, place use cases, connect actors with use cases, then run 3 scenarios.",
        instruction: "Select actors and use cases, then connect necessary pairs. You can intentionally make wrong connections and click Run to see the system catch errors.",
        type: "RUN_DIAGRAM_SCENARIO",
        data: {
          systemLabel: "FPTU Club Management System",
          actors: [
            { id: "student", label: "Student", kind: "human" },
            { id: "member", label: "Club Member", kind: "human" },
            { id: "lead", label: "Club Board", kind: "human" },
            { id: "admin", label: "Admin", kind: "human" },
            { id: "time", label: "07:00 daily", kind: "time" },
            { id: "email", label: "Email Gateway", kind: "system" },
          ],
          useCases: [
            { id: "list", label: "View club list" },
            { id: "search", label: "Search club info" },
            { id: "detail", label: "View club details" },
            { id: "internal", label: "View internal activities" },
            { id: "event", label: "Create event" },
            { id: "approve", label: "Approve club info" },
            { id: "send", label: "Send meeting reminder email" },
          ],
          distractors: [
            { id: "table", label: "Club Table" },
            { id: "controller", label: "SearchClubController" },
            { id: "button", label: "Search Button" },
          ],
          correctConnections: [c("student", "list"), c("student", "search"), c("student", "detail"), c("member", "internal"), c("lead", "event"), c("admin", "approve"), c("time", "send"), c("email", "send")],
          scenarios: [
            { id: "find", title: "Student finds club", path: ["Student", "View club list", "Search club info", "View club details"], requiredActors: ["student"], requiredUseCases: ["list", "search", "detail"], requiredConnections: [c("student", "list"), c("student", "search"), c("student", "detail")], feedback: "Missing Student flow: view list, search, or view details." },
            { id: "event", title: "Board creates event", path: ["Club Board", "Create event"], requiredActors: ["lead"], requiredUseCases: ["event"], requiredConnections: [c("lead", "event")], feedback: "Club Board must be connected to Create event." },
            { id: "reminder", title: "Auto-send reminder", path: ["07:00 daily", "Send meeting reminder email", "Email Gateway"], requiredActors: ["time", "email"], requiredUseCases: ["send"], requiredConnections: [c("time", "send"), c("email", "send")], feedback: "Automated scenario needs Time Actor and Email Gateway connected to the send email use case." },
          ],
          successSimulation: "All 3 scenarios ran successfully. Your first diagram correctly describes actors, boundary, use cases, and associations.",
        },
      },
    ],
  },
];
